//! Emit a `proposed_splits.txt` listing candidate TU boundaries derived from
//! detected vtables. Output is *not* directly consumable by jeff — it is
//! paste-bait for `config/45410914/splits.txt` after human review.
//!
//! Format per block:
//! ```text
//! # vtable @ 0x82015820  (24 virtuals)  EH magic: 0x19930521 within 0x40: yes
//! # .text hull: 0x82261A40..0x82262E80  (0x1440 bytes)
//! # .rdata hull: 0x82015820..0x82015880 (0x60 bytes)
//! class_82015820.cpp:
//!     .text  start:0x82261A40 end:0x82262E80
//!     .rdata start:0x82015820 end:0x82015880
//! ```

use std::io::Write;

use anyhow::{Context, Result};
use typed_path::Utf8NativePath;

use crate::{
    analysis::pass::VtableCandidate,
    obj::ObjInfo,
    util::file::buf_writer,
};

/// Sort candidates ascending by rdata addr, then write the file.
pub fn write_proposed_splits(
    out_path: &Utf8NativePath,
    _obj: &ObjInfo,
    vtables: &[VtableCandidate],
) -> Result<()> {
    let mut w =
        buf_writer(out_path).with_context(|| format!("opening {}", out_path))?;

    writeln!(
        w,
        "# Generated by jeff FindXboxVtables — DO NOT EDIT — paste-bait for splits.txt"
    )?;
    writeln!(w, "# candidates: {}", vtables.len())?;

    let mut sorted: Vec<&VtableCandidate> = vtables.iter().collect();
    sorted.sort_by_key(|c| (c.rdata_addr.section, c.rdata_addr.address));

    for cand in sorted {
        let rdata_lo = cand.rdata_addr.address;
        let rdata_hi = rdata_lo + cand.fn_count * 4;
        let (text_lo_sa, text_hi_sa) = cand.text_hull;
        let text_lo = text_lo_sa.address;
        let text_hi = text_hi_sa.address;
        let eh_str = match cand.eh_magic_nearby {
            Some(v) => format!("EH magic: {:#010X} within 0x40: yes", v),
            None => "EH magic within 0x40: no".to_string(),
        };

        writeln!(w)?;
        writeln!(
            w,
            "# vtable @ {:#010X}  ({} virtuals)  {}",
            rdata_lo, cand.fn_count, eh_str
        )?;
        writeln!(
            w,
            "# .text hull: {:#010X}..{:#010X}  ({:#X} bytes)",
            text_lo,
            text_hi,
            text_hi.saturating_sub(text_lo)
        )?;
        writeln!(
            w,
            "# .rdata hull: {:#010X}..{:#010X}  ({:#X} bytes)",
            rdata_lo,
            rdata_hi,
            rdata_hi - rdata_lo
        )?;
        writeln!(w, "class_{:08X}.cpp:", rdata_lo)?;
        writeln!(w, "    .text  start:{:#010X} end:{:#010X}", text_lo, text_hi)?;
        writeln!(w, "    .rdata start:{:#010X} end:{:#010X}", rdata_lo, rdata_hi)?;
    }

    w.flush()?;
    Ok(())
}
