#!/usr/bin/env python3
"""A/B two objdiff `report generate` JSONs, per unit and per symbol.

Usage: t7_report_ab.py <before.json> <after.json> [--json <path>]

Prints:
  * project measures, before -> after, with deltas
  * unit-set and symbol-set skew (a symbol present in one arm only)
  * every symbol whose fuzzy_match_percent or match_percent_normalized moved,
    with the direction, sorted by magnitude
  * the direction tally: improved / worsened / unchanged

Both reports must have been generated by the SAME objdiff-cli binary, or the
ruler is a second variable and none of this is attributable to the splitter.
"""
import json
import sys


def load(p):
    d = json.load(open(p))
    units = {}
    syms = {}
    for u in d["units"]:
        units[u["name"]] = u["measures"]
        for f in u.get("functions", []):
            syms[(u["name"], f["name"], f.get("address"))] = (
                f.get("fuzzy_match_percent"), f.get("match_percent_normalized"), f.get("size"))
    return d["measures"], units, syms


def main():
    before, after = sys.argv[1], sys.argv[2]
    out_json = None
    if "--json" in sys.argv:
        out_json = sys.argv[sys.argv.index("--json") + 1]
    mb, ub, sb = load(before)
    ma, ua, sa = load(after)

    print("== project measures")
    for k in sorted(set(mb) | set(ma)):
        x, y = mb.get(k), ma.get(k)
        try:
            dx = float(y) - float(x)
        except (TypeError, ValueError):
            dx = None
        flag = "" if (dx is None or abs(dx) < 1e-9) else "   <== MOVED"
        print("   %-28s %-18s -> %-18s %s%s"
              % (k, x, y, ("%+.6f" % dx) if dx is not None else "", flag))

    print()
    print("== set skew")
    print("   units only in before: %d   only in after: %d"
          % (len(set(ub) - set(ua)), len(set(ua) - set(ub))))
    print("   symbols only in before: %d   only in after: %d"
          % (len(set(sb) - set(sa)), len(set(sa) - set(sb))))
    for k in sorted(set(sb) ^ set(sa))[:20]:
        print("      skew: %s" % (k,))

    moved = []
    for k in sorted(set(sb) & set(sa)):
        fb, nb, zb = sb[k]
        fa, na, za = sa[k]
        if (fb, nb, zb) != (fa, na, za):
            moved.append((k, fb, fa, nb, na, zb, za))

    up = sum(1 for m in moved if (m[2] or 0) > (m[1] or 0))
    down = sum(1 for m in moved if (m[2] or 0) < (m[1] or 0))
    flat = len(moved) - up - down
    print()
    print("== per-symbol movement")
    print("   symbols compared: %d" % len(set(sb) & set(sa)))
    print("   moved: %d   fuzzy up: %d   fuzzy down: %d   fuzzy equal but other field moved: %d"
          % (len(moved), up, down, flat))
    print()
    for k, fb, fa, nb, na, zb, za in sorted(moved, key=lambda m: -abs((m[2] or 0) - (m[1] or 0))):
        print("   %-46s %-58s fuzzy %s -> %s (%+.5f)  norm %s -> %s  size %s -> %s"
              % (k[0], k[1][:58], fb, fa, (fa or 0) - (fb or 0), nb, na, zb, za))

    if out_json:
        json.dump(dict(
            before=before, after=after,
            measures_before=mb, measures_after=ma,
            moved=[dict(unit=k[0], symbol=k[1], address=k[2],
                        fuzzy_before=fb, fuzzy_after=fa,
                        norm_before=nb, norm_after=na, size_before=zb, size_after=za)
                   for k, fb, fa, nb, na, zb, za in moved],
            skew=dict(only_before=[list(k) for k in sorted(set(sb) - set(sa))],
                      only_after=[list(k) for k in sorted(set(sa) - set(sb))]),
        ), open(out_json, "w"), indent=1)


if __name__ == "__main__":
    main()
