// ============================================================================
// Ghidra Headless Decompilation of CFA Tests
// Processor: PowerPC:BE:64:Xenon (Xbox 360)
// Generated by: scripts/ghidra_decompile_cfa.py
// ============================================================================

// ============================================================================
// Test 0: func @ 0x82000000
// ============================================================================


undefined8 test_0(void)

{
  return 0;
}



// ============================================================================
// Test 1: func @ 0x82086990
// ============================================================================


void test_1(undefined8 *param_1,undefined8 param_2)

{
  int iStack_20;
  undefined4 *puStack_1c;
  undefined4 uStack_18;
  
  if (*(int *)((int)param_1 + 4) != 0) {
    iStack_20 = (int)((ulonglong)param_1[2] >> 0x20);
    if (0 < iStack_20) {
      puStack_1c = (undefined4 *)param_1[2];
      uStack_18 = (undefined4)((ulonglong)*param_1 >> 0x20);
                    /* WARNING: Could not recover jumptable at 0x820869f8. Too many branches */
                    /* WARNING: Treating indirect jump as call */
      (**(code **)(((uint)puStack_1c[1] >> 0x1d) * 4 + -0x7df79604))
                (uStack_18,param_2,uStack_18,iStack_20,*puStack_1c,0);
      return;
    }
  }
  return;
}



// ============================================================================
// Test 2: func @ 0x827f93f0
// ============================================================================


undefined8 test_2(double param_1,int param_2,undefined8 param_3,float *param_4)

{
  undefined8 uVar1;
  
  switch(*(undefined4 *)(param_2 + 0xa68)) {
  case 0:
  case 3:
    break;
  case 1:
    if (param_1 < (double)*(float *)(param_2 + 0xa5c)) {
      *param_4 = *(float *)(param_2 + 0xa5c);
      return 1;
    }
    break;
  case 2:
    if (((double)*(float *)(param_2 + 0xa60) < param_1) && (*(char *)(param_2 + 0xa6f) == '\0')) {
      *param_4 = *(float *)(param_2 + 0xa60);
      return 1;
    }
    break;
  default:
    uVar1 = func_0x83910388();
    func_0x839102e0(uVar1,0xffffffff8202b628,0x15f);
    func_0x8368d180();
  }
  *param_4 = (float)param_1;
  return 0;
}



// ============================================================================
// Test 3: func @ 0x82fbb358
// ============================================================================


void test_3(undefined8 param_1,ulonglong param_2,longlong param_3,undefined8 param_4,int param_5)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  ulonglong in_r0;
  uint uVar3;
  longlong lVar4;
  undefined1 auVar5 [16];
  undefined1 auVar6 [16];
  undefined1 auVar7 [16];
  undefined1 auVar8 [16];
  undefined1 in_vs42 [16];
  undefined1 in_vs43 [16];
  undefined1 auVar9 [16];
  undefined1 auVar10 [16];
  undefined4 uVar11;
  float fVar12;
  undefined4 uVar13;
  undefined4 uVar14;
  undefined1 in_vr3 [16];
  undefined1 auVar15 [16];
  float in_register_00010040;
  float in_register_00010044;
  float in_register_00010048;
  float in_vr4;
  float in_register_00010054;
  float in_register_00010058;
  undefined1 in_vr9 [16];
  float in_register_000100c0;
  float in_register_000100c4;
  float in_register_000100c8;
  float in_vr12;
  undefined1 auStack_20 [24];
  
  uVar3 = (uint)param_2;
  lVar4 = (param_2 - 3 & 0x3fffffff) * 4 + param_3;
  auVar5 = loadVectorRightIndexed128(0x10,lVar4);
  auVar9 = loadVectorLeftIndexed128(in_r0,lVar4);
  param_3 = (param_2 & 0x3fffffff) * 4 + param_3;
  auVar6 = in_vs43 >> 0x60;
  auVar8 = auVar6 & (undefined1  [16])0xffffffff | auVar6 << 0x20 | auVar6 << 0x40 | auVar6 << 0x60;
  auVar7 = loadVectorRightIndexed128(0x10,param_3);
  auVar6 = loadVectorLeftIndexed128(in_r0,param_3);
  vectorAddFloatingPoint((auVar9 | auVar5) ^ auVar5,auVar8);
  auVar8 = vectorSubtractFloatingPoint(auVar6 | auVar7,auVar8);
  auVar6 = in_vs42;
  fVar12 = in_register_00010058;
  if (0 < (int)uVar3) {
    do {
      auVar9 = vectorAddFloatingPoint(auVar8,auVar5);
      param_2 = param_2 - 1;
      auVar10 = vectorReciprocalEstimateFloatingPoint(auVar9);
      auVar9 = vectorNegativeMultiplySubtractFloatingPoint(auVar10,auVar9,in_vs42);
      vectorMultiplyAddFloatingPoint(auVar9,auVar10,auVar10);
      auVar9._8_8_ = in_vr3._8_8_;
      auVar9._4_4_ = in_register_00010054 * in_register_000100c4 * in_register_00010044;
      auVar9._0_4_ = in_register_00010054 * in_register_000100c0 * in_register_00010040;
      auVar15._0_8_ = auVar9._0_8_;
      auVar15._8_4_ = fVar12 * in_register_000100c8 * in_register_00010048;
      auVar15._12_4_ = in_register_00010058 * in_vr12 * in_vr4;
      in_vr3 = vectorRotateLeftImmediateMaskInsert128(auVar15,in_vr9,1,0);
      in_vr12 = in_vr3._12_4_;
      in_register_000100c8 = in_vr3._0_4_;
      auVar9 = vectorMultiplyAddFloatingPoint(auVar8,auVar10,auVar6);
      auVar6 = vectorConditionalSelect(auVar9,auVar6,auVar7);
      fVar12 = in_register_00010054;
      in_register_000100c4 = in_register_000100c8;
      in_register_000100c0 = in_vr12;
    } while (param_2 != 0);
  }
  puVar1 = (undefined4 *)((uint)(auStack_20 + (int)in_r0) & 0xfffffff0);
  uVar11 = puVar1[1];
  uVar13 = puVar1[2];
  uVar14 = puVar1[3];
  auVar5 = (undefined1  [16])0x0;
  if (uVar3 < 4) {
    in_r0 = (ulonglong)*(uint *)(uVar3 * 4 + -0x7d044b9c);
    switch(uVar3) {
    case 3:
      auVar5 = vectorMultiplyAddFloatingPoint
                         (auVar8,auVar6 & (undefined1  [16])0xffffffff | auVar6 << 0x20 |
                                 (auVar6 & (undefined1  [16])0xffffffff) << 0x40 | auVar6 << 0x60,
                          (undefined1  [16])0x0);
    case 2:
      auVar7 = auVar6 >> 0x20;
      auVar5 = vectorMultiplyAddFloatingPoint
                         (auVar8,auVar7 & (undefined1  [16])0xffffffff | auVar7 << 0x20 |
                                 (auVar7 & (undefined1  [16])0xffffffff) << 0x40 | auVar7 << 0x60,
                          auVar5);
    case 1:
      auVar7 = auVar6 >> 0x40;
      auVar5 = vectorMultiplyAddFloatingPoint
                         (auVar8,auVar7 & (undefined1  [16])0xffffffff | auVar7 << 0x20 |
                                 (auVar7 & (undefined1  [16])0xffffffff) << 0x40 | auVar7 << 0x60,
                          auVar5);
    case 0:
      auVar7 = auVar6 >> 0x60;
      vectorMultiplyAddFloatingPoint
                (auVar6,auVar7 & (undefined1  [16])0xffffffff | auVar7 << 0x20 | auVar7 << 0x40 |
                        auVar7 << 0x60,auVar5);
    }
  }
  puVar2 = (undefined4 *)((int)in_r0 + param_5 & 0xfffffff0);
  *puVar2 = *puVar1;
  puVar2[1] = uVar11;
  puVar2[2] = uVar13;
  puVar2[3] = uVar14;
  return;
}



// ============================================================================
// Test 4: func @ 0x822c4618
// ============================================================================


ulonglong test_4(void)

{
  int iVar2;
  longlong lVar1;
  ulonglong uVar3;
  byte abStack_10 [2];
  undefined2 auStack_e [7];
  
  auStack_e[0] = 0;
  iVar2 = func_0x82960d34(3,0xe,abStack_10,1,auStack_e);
  if (iVar2 < 0) {
LAB_822c47b4:
    uVar3 = 0;
  }
  else {
    switch(abStack_10[0]) {
    case 5:
      uVar3 = 2;
      break;
    case 6:
      uVar3 = 1;
      break;
    default:
      goto LAB_822c47b4;
    case 8:
      uVar3 = 3;
      break;
    case 0xd:
      uVar3 = 4;
      break;
    case 0x10:
      uVar3 = 5;
      break;
    case 0x12:
      uVar3 = 0x21;
      break;
    case 0x13:
      uVar3 = 6;
      break;
    case 0x14:
      uVar3 = 7;
      break;
    case 0x15:
      uVar3 = 8;
      break;
    case 0x17:
      uVar3 = 9;
      break;
    case 0x18:
      uVar3 = 0xd;
      break;
    case 0x19:
      uVar3 = 10;
      break;
    case 0x1f:
      uVar3 = 0x1f;
      break;
    case 0x20:
      uVar3 = 0xb;
      break;
    case 0x22:
      uVar3 = 0xc;
      break;
    case 0x23:
      uVar3 = 0x23;
      break;
    case 0x25:
      uVar3 = 0xe;
      break;
    case 0x27:
      uVar3 = 0xf;
      break;
    case 0x2a:
      uVar3 = 0x10;
      break;
    case 0x2c:
      uVar3 = 0x12;
      break;
    case 0x2e:
      uVar3 = 0x11;
      break;
    case 0x32:
      uVar3 = 0x13;
      break;
    case 0x35:
      uVar3 = 0x14;
      break;
    case 0x38:
      uVar3 = 0x15;
      break;
    case 0x47:
      uVar3 = 0x16;
      break;
    case 0x4a:
      uVar3 = 0x17;
      break;
    case 0x4b:
      uVar3 = 0x19;
      break;
    case 0x4c:
      uVar3 = 0x18;
      break;
    case 0x52:
      uVar3 = 0x1a;
      break;
    case 0x54:
      uVar3 = 0x1b;
      break;
    case 0x58:
      uVar3 = 0x25;
      break;
    case 0x5a:
      uVar3 = 0x20;
      break;
    case 0x5b:
      uVar3 = 0x1c;
      break;
    case 0x5d:
      uVar3 = 0x1d;
      break;
    case 0x65:
      uVar3 = 0x22;
      break;
    case 0x67:
      uVar3 = 0x24;
      break;
    case 0x6d:
      uVar3 = 0x1e;
    }
  }
  if ((uVar3 == 0) || (0x25 < uVar3)) {
    lVar1 = func_0x82960854();
    uVar3 = (ulonglong)(lVar1 << 0x20) >> 0x28 & 0xff;
    if (uVar3 == 1) {
      uVar3 = ((ulonglong)(LZCOUNT((int)lVar1 + -0x101) << 0x20) >> 0x25 ^ 1) + 0x14;
    }
    else {
      uVar3 = ((ulonglong)(LZCOUNT((int)uVar3 + -2) << 0x20) >> 0x25 ^ 1) + 0x23;
    }
  }
  return uVar3;
}



// ============================================================================
// Test 5: func @ 0x824afd20
// ============================================================================


double test_5(undefined8 param_1,int *param_2)

{
  undefined4 *puVar1;
  float fVar2;
  undefined1 *puVar4;
  int iVar5;
  undefined8 uVar3;
  double dVar6;
  double dVar7;
  undefined4 auStack_70 [2];
  undefined1 auStack_68 [8];
  undefined1 auStack_60 [8];
  undefined1 auStack_58 [8];
  undefined1 auStack_50 [8];
  undefined1 auStack_48 [8];
  undefined1 auStack_40 [8];
  undefined1 auStack_38 [8];
  undefined1 auStack_30 [8];
  undefined1 auStack_28 [8];
  undefined1 auStack_20 [16];
  
  func_0x830b1ec0(auStack_70);
  auStack_70[0] = 0x8202c418;
  func_0x830b1f98(auStack_70,0);
  puVar1 = (undefined4 *)*param_2;
  switch(*puVar1) {
  case 0:
  case 1:
  case 2:
  case 3:
  case 0x12:
  case 0x15:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_68,uVar3,0xffffffff8202d980);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_68;
    break;
  case 4:
  case 5:
  case 6:
  case 7:
  case 8:
  case 9:
  case 10:
  case 0xb:
  case 0xc:
  case 0xd:
  case 0xe:
  case 0xf:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_60,uVar3,0xffffffff8200d504);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_60;
    break;
  case 0x10:
  case 0x13:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_58,uVar3,0xffffffff82010bc0);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_58;
    break;
  case 0x11:
  case 0x14:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_50,uVar3,0xffffffff82010ba8);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_50;
    break;
  case 0x16:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_48,uVar3,0xffffffff8202d974);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_48;
    break;
  case 0x17:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_40,uVar3,0xffffffff8202d968);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_40;
    break;
  case 0x18:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_38,uVar3,0xffffffff8202d95c);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_38;
    break;
  case 0x19:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_30,uVar3,0xffffffff8202d94c);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_30;
    break;
  case 0x1a:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_28,uVar3,0xffffffff8202d93c);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_28;
    break;
  case 0x1b:
    uVar3 = func_0x830b1f28(puVar1 + 1);
    uVar3 = func_0x830b4918(auStack_20,uVar3,0xffffffff8202d930);
    func_0x830b2028(auStack_70,uVar3);
    puVar4 = auStack_20;
    break;
  default:
    goto LAB_824aff70;
  }
  func_0x830b1ed8(puVar4);
LAB_824aff70:
  iVar5 = func_0x830b1f80(auStack_70);
  fVar2 = fRam8200d72c;
  if (iVar5 != 0) {
    uVar3 = func_0x830b1f28(auStack_70);
    func_0x830b1f28(auStack_70);
    dVar6 = (double)func_0x830b6ed8();
    dVar7 = (double)func_0x830b72f8(uVar3);
    fVar2 = (float)(dVar6 * dVar7);
  }
  dVar6 = (double)fVar2;
  func_0x830b1ed8(auStack_70);
  return dVar6;
}



// ============================================================================
// Test 6: func @ 0x8219b550
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_6(void)

{
  int iVar1;
  ulonglong uVar2;
  uint uVar3;
  ulonglong uVar4;
  int *piVar5;
  int iVar6;
  int iVar7;
  short *psVar8;
  int iStack_a0;
  
  iVar1 = func_0x82278b30();
  psVar8 = (short *)(iVar1 + 0x34);
  iStack_a0 = 0;
  iVar6 = 0;
  iVar7 = 0;
  for (uVar4 = (ulonglong)*(uint *)(iVar1 + 0x18); uVar4 != 0; uVar4 = uVar4 - 1) {
    if (*psVar8 != 0) {
      func_0x8214c430(0xffffffff82002ae0,0xffffffff82004700);
    }
    switch(*(undefined1 *)((int)psVar8 + 9)) {
    case 0:
      if (*(char *)(psVar8 + 5) != '\0') {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff8200471c);
      }
      iStack_a0 = *(int *)(psVar8 + 2);
      break;
    case 1:
      if (*(char *)(psVar8 + 5) != '\0') {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff8200471c);
      }
      iVar6 = *(int *)(psVar8 + 2);
      break;
    case 2:
      if (*(char *)(psVar8 + 5) != '\0') {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff8200471c);
      }
      iVar7 = *(int *)(psVar8 + 2);
      break;
    case 3:
      if (*(int *)(psVar8 + 2) != 0x2a23b9) {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff8200476c);
      }
      if (*(char *)(psVar8 + 5) != '\0') {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff8200471c);
      }
      break;
    case 4:
      if (*(int *)(psVar8 + 2) != 0x2c83a4) {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff82004798);
      }
      if (*(char *)(psVar8 + 5) != '\0') {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff8200471c);
      }
      break;
    case 5:
      uVar2 = (ulonglong)*(uint *)(psVar8 + 2);
      if ((((uVar2 != 0x1a23a6) && (uVar2 != 0x2a23b9)) && (uVar2 - 0x2c23a5 != 0)) &&
         ((uVar2 - 0x2c23a5 & 0xffffffff) != 0x5fff)) {
        func_0x8214c430(0xffffffff82004830);
      }
      break;
    default:
      func_0x8214c430(0xffffffff82004840);
      break;
    case 9:
      func_0x8214c430(0xffffffff8200473c);
      break;
    case 10:
      if (*(int *)(psVar8 + 2) != 0x182886) {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff820047c4);
      }
      if (1 < *(byte *)(psVar8 + 5)) {
        func_0x8214c430(0xffffffff82002ae0,0xffffffff820047f0);
      }
    }
    psVar8 = psVar8 + 6;
  }
  uVar3 = 0;
  piVar5 = (int *)0x820043e8;
  while (((*piVar5 != iStack_a0 || (piVar5[1] != iVar7)) || (piVar5[2] != iVar6))) {
    uVar3 = uVar3 + 0x10;
    piVar5 = piVar5 + 4;
    if (0x10f < uVar3) {
LAB_8219b83c:
      func_0x8214c430(0xffffffff82004688,iStack_a0,iVar7,iVar6);
                    /* WARNING: Bad instruction - Truncating control flow here */
      halt_baddata();
    }
  }
  if (piVar5[3] != 0) {
    halt_baddata();
  }
  goto LAB_8219b83c;
}



// ============================================================================
// Test 7: func @ 0x821c3e88
// ============================================================================


void test_7(uint *param_1)

{
  int *piVar1;
  int iVar2;
  uint uVar3;
  undefined8 uVar4;
  
  if ((*param_1 & 0x100000) == 0) {
    func_0x8214c430(0xffffffff82008d40);
  }
  iVar2 = func_0x82141160();
  piVar1 = piRam82710644;
  if (iVar2 == 2) {
    piVar1 = piRam82710640;
  }
  iVar2 = *piVar1;
  uVar3 = *param_1;
  switch(uVar3 & 0xf) {
  case 1:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      func_0x82158ea0(iVar2,param_1[2],9,param_1,0);
    }
    uVar3 = param_1[6] & 0xfffffffc;
    goto code_r0x821c3fc4;
  case 2:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      uVar4 = 0xb;
code_r0x821c4038:
      func_0x82158ea0(iVar2,param_1[2],uVar4,param_1,0);
    }
    goto code_r0x821c404c;
  case 3:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      func_0x82158ea0(iVar2,param_1[2],0xd,param_1,0);
    }
    func_0x8214df40(param_1,1,1);
    uVar3 = param_1[0xc] & 0xfffff000;
    func_0x8214e210(param_1[8] & 0xfffff000,3);
    goto code_r0x821c3fc4;
  case 4:
    if ((uVar3 & 0x40000000) == 0) {
      if ((uVar3 & 0x80000000) != 0) {
        func_0x8213abd0(param_1[7] & 0xfff,(ulonglong)param_1[0xb] / 0x1400);
      }
      if ((param_1[8] & 1) != 0) {
        uRam826fe644 = 0;
      }
    }
    break;
  case 6:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      func_0x82158ea0(iVar2,param_1[2],7,param_1,0);
    }
    uVar3 = param_1[8];
    goto code_r0x821c3fc4;
  case 7:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      uVar4 = 8;
      goto code_r0x821c4038;
    }
    goto code_r0x821c404c;
  case 8:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      uVar4 = 0x11;
      goto code_r0x821c4038;
    }
code_r0x821c404c:
    uVar3 = param_1[6];
code_r0x821c3fc4:
    func_0x8214e210(uVar3,3);
    break;
  case 9:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      func_0x82158ea0(iVar2,param_1[2],0xf,param_1,0);
    }
    func_0x82134c50(param_1);
    break;
  case 10:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      func_0x82158ea0(iVar2,param_1[2],0x15,param_1,0);
    }
    func_0x82159280(param_1);
    break;
  case 0xb:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      func_0x82158ea0(iVar2,param_1[2],0x17,param_1,0);
    }
    func_0x82148ba0(param_1);
    break;
  case 0xc:
    if ((param_1[2] != 0) && (iVar2 != 0)) {
      func_0x82161cd0(iVar2,0);
      func_0x82158ea0(iVar2,param_1[2],0x19,param_1,0);
    }
    func_0x821394d0(param_1);
  }
  *param_1 = 0xf;
  func_0x821553e0(param_1);
  return;
}



// ============================================================================
// Test 8: func @ 0x823178b0
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_8(void)

{
  int iVar1;
  int *piVar2;
  int iVar3;
  undefined4 *puVar4;
  char cVar5;
  ulonglong uVar6;
  ulonglong uVar7;
  double dVar8;
  double dVar9;
  undefined1 auStack_60 [4];
  undefined1 auStack_5c [4];
  undefined1 auStack_58 [4];
  undefined1 auStack_54 [4];
  undefined1 auStack_50 [4];
  undefined4 uStack_4c;
  undefined1 auStack_48 [4];
  undefined1 auStack_44 [4];
  undefined4 uStack_40;
  uint uStack_3c;
  undefined4 uStack_38;
  uint uStack_34;
  undefined4 uStack_30;
  uint uStack_2c;
  
  iVar1 = func_0x82624b1c();
  uVar7 = 0xffffffffffffffff;
  switch(*(undefined4 *)(iVar1 + 0x54)) {
  case 0:
    cVar5 = func_0x82254db8(uRam82a41fcc);
    if (cVar5 == '\0') {
      halt_baddata();
    }
    cVar5 = func_0x82252590(uRam82a41fcc);
    goto code_r0x8231791c;
  case 1:
    cVar5 = func_0x8236f4f8(*(undefined4 *)(iVar1 + 0x4c));
code_r0x8231791c:
    if (cVar5 != '\0') {
      halt_baddata();
    }
    uVar7 = 3;
    break;
  case 2:
    cVar5 = func_0x8236f4f8(*(undefined4 *)(iVar1 + 0x4c));
    if (cVar5 != '\0') {
      halt_baddata();
    }
    func_0x82317638(iVar1,0xffffffffffffffff);
    puVar4 = (undefined4 *)func_0x82512998(auStack_60,0xffffffff82047a90);
    func_0x821d3c98(auStack_50,*puVar4);
    iVar3 = *(int *)(*(int *)(iVar1 + 4) + 4) + iVar1;
    (**(code **)(*(int *)(iVar3 + 4) + 0x18))(&uStack_40,iVar3 + 4,uStack_4c,1);
    if ((uStack_3c & 0x10) != 0) {
      func_0x821d0348(uStack_40);
    }
    *(undefined1 *)(iVar1 + 0x120) = 1;
    goto code_r0x823179c4;
  case 3:
    cVar5 = func_0x8236f4f8(*(undefined4 *)(iVar1 + 0x4c));
    if (cVar5 != '\0') {
      halt_baddata();
    }
    piVar2 = (int *)func_0x82315b08(auStack_5c,*(undefined4 *)(iVar1 + 0x100));
    if (*piVar2 == iRam829feaa8) {
      piVar2 = (int *)func_0x82315a00(auStack_54,*(undefined4 *)(iVar1 + 0x100));
      if (*piVar2 == iRam829feaa8) {
        halt_baddata();
      }
      uVar7 = 4;
    }
    else {
      puVar4 = (undefined4 *)func_0x82315b08(auStack_58);
      uVar7 = 0xb;
      *(undefined4 *)(iVar1 + 0x74) = *puVar4;
    }
    break;
  default:
    goto LAB_82317c44;
  case 5:
    cVar5 = func_0x82315e20(*(undefined4 *)(iVar1 + 0x104));
    if (cVar5 != '\0') {
      dVar9 = (double)(*(float *)(iVar1 + 0x5c) - *(float *)(iVar1 + 0x108));
      dVar8 = (double)func_0x82315c10(*(undefined4 *)(iVar1 + 0x100));
      if (dVar9 <= dVar8) {
        func_0x82252dd8(uRam82a41fcc,0);
        iVar3 = func_0x822848b8();
        if (iVar3 < 100) {
          halt_baddata();
        }
      }
    }
    cVar5 = func_0x82315f28(*(undefined4 *)(iVar1 + 0x104));
    if (cVar5 == '\0') {
      uVar7 = 7;
    }
    else {
      if (*(float *)(iVar1 + 0x5c) < *(float *)(iVar1 + 0x10c)) {
        *(float *)(iVar1 + 0x10c) = *(float *)(iVar1 + 0x5c);
      }
      dVar9 = (double)(*(float *)(iVar1 + 0x5c) - *(float *)(iVar1 + 0x10c));
      dVar8 = (double)func_0x82315d18(*(undefined4 *)(iVar1 + 0x100));
      if (dVar9 < dVar8) {
        halt_baddata();
      }
      uVar7 = 6;
    }
    break;
  case 6:
    cVar5 = func_0x8236f4f8(*(undefined4 *)(iVar1 + 0x4c));
    if (cVar5 != '\0') {
      halt_baddata();
    }
    puVar4 = (undefined4 *)func_0x82512998(auStack_48,0xffffffff82047a7c);
    func_0x821d3c98(auStack_50,*puVar4);
    iVar1 = *(int *)(*(int *)(iVar1 + 4) + 4) + iVar1;
    (**(code **)(*(int *)(iVar1 + 4) + 0x18))(&uStack_38,iVar1 + 4,uStack_4c,1);
    if ((uStack_34 & 0x10) != 0) {
      func_0x821d0348(uStack_38);
    }
code_r0x823179c4:
    func_0x821d0348(uStack_4c);
    halt_baddata();
  case 7:
    cVar5 = func_0x8236f4f8(*(undefined4 *)(iVar1 + 0x4c));
    if (cVar5 != '\0') {
      halt_baddata();
    }
    if ((uRam82a458ec & 1) == 0) {
      uRam82a458ec = uRam82a458ec | 1;
      puVar4 = (undefined4 *)func_0x82512998(auStack_44,0xffffffff82047a68);
      func_0x821d3c98(0xffffffff82a458e4,*puVar4);
      func_0x82625588(0xffffffff829d0eb8);
    }
    iVar3 = *(int *)(*(int *)(iVar1 + 4) + 4) + iVar1;
    (**(code **)(*(int *)(iVar3 + 4) + 0x18))(&uStack_30,iVar3 + 4,uRam82a458e8,1);
    if ((uStack_2c & 0x10) != 0) {
      func_0x821d0348(uStack_30);
    }
    uVar7 = 0xc;
    break;
  case 9:
    cVar5 = func_0x823156d0(iVar1);
    goto code_r0x82317c00;
  case 10:
    cVar5 = func_0x823157e8(iVar1);
code_r0x82317c00:
    if (cVar5 == '\0') {
      halt_baddata();
    }
    uVar7 = (ulonglong)*(uint *)(iVar1 + 0x58);
code_r0x82317c24:
    if ((int)uVar7 == -1) {
      halt_baddata();
    }
    break;
  case 0xb:
    func_0x82316100(iVar1);
    goto code_r0x82317c24;
  }
  uVar6 = (ulonglong)*(uint *)(iVar1 + 0x58);
  if (*(uint *)(iVar1 + 0x58) == 0xffffffff) {
    uVar6 = uVar7;
  }
  func_0x82317638(iVar1,uVar6);
LAB_82317c44:
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// ============================================================================
// Test 9: func @ 0x823349f8
// ============================================================================


undefined4 * test_9(undefined4 *param_1,undefined8 param_2,uint param_3,int param_4)

{
  uint *puVar1;
  int iVar4;
  undefined4 *puVar5;
  undefined8 uVar2;
  longlong lVar3;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  undefined4 uStack_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  undefined1 auStack_28 [16];
  
  *param_1 = uRam829feaa8;
  if (param_3 == 0) {
    func_0x82512998(&uStack_2c,0xffffffff8204e55c);
    uStack_60 = uStack_2c;
  }
  else if (param_3 == 1) {
    if (param_4 == 0) {
      func_0x82512998(&uStack_4c,0xffffffff8204e650);
      uStack_60 = uStack_4c;
    }
    else {
      iVar4 = func_0x823a52f8((ulonglong)**(uint **)(param_4 + 4) + 0x10);
      switch(iVar4 + -1) {
      case 0:
      case 1:
      case 4:
      case 5:
      case 7:
        func_0x823a52f8((ulonglong)**(uint **)(param_4 + 4) + 0x10,*(uint **)(param_4 + 4));
        func_0x82512998(&uStack_48,0xffffffff8204e650);
        uStack_60 = uStack_48;
        break;
      case 2:
        func_0x82512998(&uStack_44,0xffffffff8204e634);
        uStack_60 = uStack_44;
        break;
      case 3:
        func_0x82512998(&uStack_40,0xffffffff8204e618);
        uStack_60 = uStack_40;
        break;
      default:
        puVar1 = *(uint **)(param_4 + 4);
        lVar3 = (ulonglong)*puVar1 + 0x10;
code_r0x82334c78:
        func_0x823a52f8(lVar3,puVar1);
        return param_1;
      case 9:
        iVar4 = func_0x823a52f8((ulonglong)**(uint **)(param_4 + 4) + 0x18);
        if ((iVar4 == 0) || (iVar4 == 2)) {
          func_0x82512998(&uStack_30,0xffffffff8204e578);
          uStack_60 = uStack_30;
        }
        else if (iVar4 == 3) {
          func_0x82512998(&uStack_34,0xffffffff8204e59c);
          uStack_60 = uStack_34;
        }
        else {
          if (iVar4 != 4) {
            puVar1 = *(uint **)(param_4 + 4);
            lVar3 = (ulonglong)*puVar1 + 0x18;
            goto code_r0x82334c78;
          }
          puVar5 = (undefined4 *)func_0x82512998(auStack_28,0xffffffff8201e3f0);
          uVar2 = func_0x823b6540(*(int *)(*piRam82a42830 + 4) + (int)piRam82a42830,*puVar5,1);
          iVar4 = func_0x823a52f8(uVar2,0);
          if (iVar4 == 0) {
            func_0x82512998(&uStack_38,0xffffffff8204e5c0);
            uStack_60 = uStack_38;
          }
          else {
            func_0x82512998(&uStack_3c,0xffffffff8204e5ec);
            uStack_60 = uStack_3c;
          }
        }
      }
    }
  }
  else if (param_3 < 3) {
    func_0x82512998(&uStack_50,0xffffffff8204e670);
    uStack_60 = uStack_50;
  }
  else if (param_3 == 3) {
    func_0x82512998(&uStack_54,0xffffffff8204e68c);
    uStack_60 = uStack_54;
  }
  else if (param_3 < 5) {
    func_0x82512998(&uStack_58,0xffffffff8204e6a8);
    uStack_60 = uStack_58;
  }
  else if (param_3 == 5) {
    func_0x82512998(&uStack_5c,0xffffffff8204e6c8);
    uStack_60 = uStack_5c;
  }
  else {
    if (6 < param_3) {
      return param_1;
    }
    func_0x82512998(&uStack_60,0xffffffff8204e6f4);
  }
  *param_1 = uStack_60;
  return param_1;
}



// ============================================================================
// Test 10: func @ 0x82592db8
// ============================================================================


ulonglong test_10(int param_1)

{
  undefined4 *puVar2;
  char cVar5;
  int iVar3;
  uint *puVar4;
  ulonglong uVar1;
  undefined8 uVar6;
  undefined1 auStack_840 [4];
  undefined1 auStack_83c [12];
  undefined1 auStack_830 [2080];
  
  switch(*(undefined4 *)(param_1 + 4)) {
  case 0:
    uVar6 = func_0x823a52f8(param_1,0);
    uVar1 = func_0x823f7120(0xffffffff82071004,uVar6);
    break;
  case 1:
    func_0x823a53f8(param_1,0);
    uVar1 = func_0x823ca218(0xffffffff820c151c);
    break;
  case 2:
    func_0x823a4d30(param_1,0);
    uVar1 = func_0x823a5578();
    goto code_r0x82592e58;
  case 3:
    uVar6 = func_0x823a4d30(param_1,0);
    puVar2 = (undefined4 *)func_0x823c0100(auStack_83c,uVar6);
    uVar1 = func_0x823f7120(0xffffffff8200fe44,*puVar2);
    break;
  case 4:
    cVar5 = func_0x823a54b0(param_1);
    if (cVar5 == '\0') {
      uVar6 = 0xffffffff82067da0;
      goto code_r0x82592f2c;
    }
    iVar3 = func_0x823a5440(param_1,0);
    uVar1 = (ulonglong)*(uint *)(iVar3 + 0x18);
code_r0x82592e58:
    uVar1 = func_0x823f7120(0xffffffff8200fe44,uVar1);
    break;
  case 5:
    puVar4 = (uint *)func_0x823a5320(auStack_840,param_1,0);
    uVar1 = (ulonglong)*puVar4;
    break;
  default:
    uVar6 = 0xffffffff820c14e8;
    goto code_r0x82592f2c;
  case 0x10:
    uVar6 = 0xffffffff820c1514;
    goto code_r0x82592f2c;
  case 0x11:
    uVar6 = 0xffffffff820c1508;
    goto code_r0x82592f2c;
  case 0x12:
    uVar1 = func_0x823a53b8(param_1,0);
    break;
  case 0x13:
    uVar6 = 0xffffffff820c14fc;
    goto code_r0x82592f2c;
  case 0x14:
    uVar6 = 0xffffffff820c14f4;
code_r0x82592f2c:
    func_0x825156d8(auStack_830,uVar6);
    uVar1 = func_0x82515370(auStack_830);
  }
  return uVar1;
}



// ============================================================================
// Test 11: func @ 0x8222c138
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_11(undefined8 param_1,int param_2)

{
  byte bVar1;
  uint uVar2;
  undefined4 *puVar3;
  int *piVar4;
  ulonglong uVar5;
  undefined8 uVar6;
  undefined8 uVar7;
  
  piVar4 = (int *)func_0x8248726c();
  if (((piVar4 == (int *)0x0) || ((uint *)piVar4[7] == (uint *)0x0)) || (*piVar4 == 0)) {
                    /* WARNING: Bad instruction - Truncating control flow here */
    halt_baddata();
  }
  uVar6 = 0xfffffffffffffffb;
  if (param_2 != 4) {
    uVar6 = 0;
  }
  uVar2 = *(uint *)piVar4[7];
  uVar7 = 0xfffffffffffffffb;
joined_r0x8222c188:
  if (0xd < uVar2) {
    halt_baddata();
  }
  switch(*(ushort *)(&UNK_82020ec8 + uVar2 * 2) + 0x8222c1e0) {
  case 0x8222c1e0:
    if (piVar4[1] == 0) {
      halt_baddata();
    }
    piVar4[1] = piVar4[1] + -1;
    piVar4[2] = piVar4[2] + 1;
    *(uint *)(piVar4[7] + 4) = (uint)*(byte *)*piVar4;
    puVar3 = (undefined4 *)piVar4[7];
    uVar2 = puVar3[1];
    *piVar4 = *piVar4 + 1;
    if ((uVar2 & 0xf) == 8) {
      if (((uint)puVar3[1] >> 4) + 8 <= (uint)puVar3[4]) {
        *puVar3 = 1;
        goto code_r0x8222c26c;
      }
      *puVar3 = 0xd;
      piVar4[6] = -0x7dfdf0f0;
    }
    else {
      *puVar3 = 0xd;
      piVar4[6] = -0x7dfdf10c;
    }
    goto code_r0x8222c4c8;
  case 0x8222c26c:
code_r0x8222c26c:
    if (piVar4[1] == 0) {
      halt_baddata();
    }
    puVar3 = (undefined4 *)piVar4[7];
    piVar4[1] = piVar4[1] + -1;
    piVar4[2] = piVar4[2] + 1;
    bVar1 = *(byte *)*piVar4;
    *piVar4 = (int)((byte *)*piVar4 + 1);
    uVar5 = ((ulonglong)(uint)puVar3[1] & 0xffffff) * 0x100 + (ulonglong)bVar1;
    if (uVar5 != ((uVar5 & 0xffffffff) / 0x1f) * 0x1f) {
      *puVar3 = 0xd;
      piVar4[6] = -0x7dfdf0dc;
      goto code_r0x8222c4c8;
    }
    if ((bVar1 & 0x20) != 0) {
      *(undefined4 *)piVar4[7] = 2;
      goto code_r0x8222c500;
    }
    *puVar3 = 7;
    uVar7 = uVar6;
    break;
  case 0x8222c2e4:
    uVar7 = func_0x8222dae0(*(undefined4 *)(piVar4[7] + 0x14),piVar4,uVar7);
    if ((int)uVar7 == -3) {
      *(undefined4 *)piVar4[7] = 0xd;
      *(undefined4 *)(piVar4[7] + 4) = 0;
    }
    else {
      if ((int)uVar7 == 0) {
        uVar7 = uVar6;
      }
      if ((int)uVar7 != 1) {
        halt_baddata();
      }
      func_0x8222d930(*(undefined4 *)(piVar4[7] + 0x14),piVar4,piVar4[7] + 4);
      puVar3 = (undefined4 *)piVar4[7];
      if (puVar3[3] == 0) {
        *puVar3 = 8;
        goto code_r0x8222c364;
      }
      *puVar3 = 0xc;
      uVar7 = uVar6;
    }
    break;
  case 0x8222c364:
code_r0x8222c364:
    if (piVar4[1] == 0) {
      halt_baddata();
    }
    piVar4[1] = piVar4[1] + -1;
    piVar4[2] = piVar4[2] + 1;
    *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 << 0x18;
    *piVar4 = *piVar4 + 1;
    *(undefined4 *)piVar4[7] = 9;
  case 0x8222c3b4:
    if (piVar4[1] == 0) {
      halt_baddata();
    }
    piVar4[1] = piVar4[1] + -1;
    piVar4[2] = piVar4[2] + 1;
    *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 * 0x10000 + *(int *)(piVar4[7] + 8);
    *piVar4 = *piVar4 + 1;
    *(undefined4 *)piVar4[7] = 10;
  case 0x8222c40c:
    goto code_r0x8222c40c;
  case 0x8222c464:
    goto code_r0x8222c464;
  case 0x8222c500:
code_r0x8222c500:
    if (piVar4[1] == 0) {
      halt_baddata();
    }
    piVar4[1] = piVar4[1] + -1;
    piVar4[2] = piVar4[2] + 1;
    *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 << 0x18;
    *piVar4 = *piVar4 + 1;
    *(undefined4 *)piVar4[7] = 3;
  case 0x8222c550:
    if (piVar4[1] == 0) {
      halt_baddata();
    }
    piVar4[1] = piVar4[1] + -1;
    piVar4[2] = piVar4[2] + 1;
    *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 * 0x10000 + *(int *)(piVar4[7] + 8);
    *piVar4 = *piVar4 + 1;
    *(undefined4 *)piVar4[7] = 4;
  case 0x8222c5a8:
    goto code_r0x8222c5a8;
  case 0x8222c5fc:
    goto code_r0x8222c5fc;
  case 0x8222c65c:
    *(undefined4 *)piVar4[7] = 0xd;
    piVar4[6] = -0x7dfdf11c;
    *(undefined4 *)(piVar4[7] + 4) = 0;
    halt_baddata();
  case 0x8222c684:
    goto LAB_824872bc;
  case 0x8222c68c:
    halt_baddata();
  }
code_r0x8222c4d0:
  uVar2 = *(uint *)piVar4[7];
  goto joined_r0x8222c188;
code_r0x8222c40c:
  if (piVar4[1] == 0) {
    halt_baddata();
  }
  piVar4[1] = piVar4[1] + -1;
  piVar4[2] = piVar4[2] + 1;
  *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 * 0x100 + *(int *)(piVar4[7] + 8);
  *piVar4 = *piVar4 + 1;
  *(undefined4 *)piVar4[7] = 0xb;
code_r0x8222c464:
  if (piVar4[1] == 0) {
    halt_baddata();
  }
  piVar4[1] = piVar4[1] + -1;
  piVar4[2] = piVar4[2] + 1;
  *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 + *(int *)(piVar4[7] + 8);
  puVar3 = (undefined4 *)piVar4[7];
  *piVar4 = *piVar4 + 1;
  if (puVar3[1] == puVar3[2]) {
    *(undefined4 *)piVar4[7] = 0xc;
LAB_824872bc:
    halt_baddata();
  }
  *puVar3 = 0xd;
  piVar4[6] = -0x7dfdf0c4;
code_r0x8222c4c8:
  *(undefined4 *)(piVar4[7] + 4) = 5;
  uVar7 = uVar6;
  goto code_r0x8222c4d0;
code_r0x8222c5a8:
  if (piVar4[1] == 0) {
    halt_baddata();
  }
  piVar4[1] = piVar4[1] + -1;
  piVar4[2] = piVar4[2] + 1;
  *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 * 0x100 + *(int *)(piVar4[7] + 8);
  *piVar4 = *piVar4 + 1;
  *(undefined4 *)piVar4[7] = 5;
code_r0x8222c5fc:
  if (piVar4[1] != 0) {
    piVar4[1] = piVar4[1] + -1;
    piVar4[2] = piVar4[2] + 1;
    *(uint *)(piVar4[7] + 8) = (uint)*(byte *)*piVar4 + *(int *)(piVar4[7] + 8);
    *piVar4 = *piVar4 + 1;
    piVar4[0xc] = ((undefined4 *)piVar4[7])[2];
    *(undefined4 *)piVar4[7] = 6;
    halt_baddata();
  }
  halt_baddata();
}



// ============================================================================
// Test 12: func @ 0x8229f7f0
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_12(undefined8 param_1,undefined4 param_2,ulonglong param_3)

{
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  ulonglong uVar1;
  int iVar5;
  undefined8 uVar6;
  longlong lVar7;
  uint uVar8;
  bool bVar9;
  int iStack_70;
  int iStack_6c;
  int iStack_68;
  
  iVar2 = func_0x82487284();
  iVar4 = 0;
  if (0x10 < (param_3 & 0xffffffff)) {
    *(undefined4 *)(iVar2 + 0x44) = 1;
  }
  if (*(int *)(iVar2 + 0x44) != 0) {
    halt_baddata();
  }
  func_0x82487ed0((param_3 & 0x3fffffff) * 4 + (ZEXT48(&stack0x00000000) - 0x70),0,
                  (0x10 - param_3 & 0x3fffffff) << 2);
  param_3 = param_3 - 1;
  if (-1 < (longlong)param_3) {
    lVar7 = (param_3 & 0x3fffffff) * 4 + (ZEXT48(&stack0x00000000) - 0x70);
    do {
      iVar5 = *(int *)(iVar2 + 0x5c);
      if (iVar5 == 0) {
        uVar6 = 0xffffffff8202c0f4;
        goto LAB_8229f8cc;
      }
      param_3 = param_3 - 1;
      uVar3 = *(undefined4 *)(iVar5 + 8);
      *(undefined4 *)(iVar2 + 0x5c) = *(undefined4 *)(iVar5 + 0xc);
      *(undefined4 *)lVar7 = uVar3;
      lVar7 = lVar7 + -4;
      *(undefined4 *)(iVar5 + 8) = 0;
      *(undefined4 *)(iVar5 + 0xc) = *(undefined4 *)(iVar2 + 0x60);
      *(int *)(iVar2 + 0x60) = iVar5;
    } while (-1 < (longlong)param_3);
  }
  switch(param_2) {
  case 0:
    func_0x8229eae0(iVar2,*(undefined4 *)(iStack_70 + 0x18),1);
    break;
  case 1:
    func_0x8229dcc8(iVar2,*(undefined4 *)(iStack_70 + 0x18));
    break;
  case 2:
    *(undefined4 *)(*(int *)(iVar2 + 0x26c) + 0x1c) = *(undefined4 *)(iStack_70 + 0x18);
    if (*(int *)(iVar2 + 0x278) != 0xc) {
      *(int *)(*(int *)(iVar2 + 0x26c) + 0x1c) = *(int *)(*(int *)(iVar2 + 0x26c) + 0x1c) + -1;
    }
    break;
  case 3:
    iVar5 = *(int *)(iStack_6c + 0x18);
    *(undefined4 *)(*(int *)(iVar2 + 0x26c) + 0x1c) = *(undefined4 *)(iStack_70 + 0x18);
    if (*(int *)(iVar2 + 0x278) != 0xc) {
      *(int *)(*(int *)(iVar2 + 0x26c) + 0x1c) = *(int *)(*(int *)(iVar2 + 0x26c) + 0x1c) + -1;
    }
    if (iVar5 != 0) {
      *(int *)(*(int *)(iVar2 + 0x26c) + 0x18) = iVar5;
    }
    break;
  case 4:
    func_0x8229f4d0(iVar2);
    break;
  case 5:
    func_0x8229c678(iVar2);
    break;
  case 6:
    uVar1 = (ulonglong)*(uint *)(iStack_70 + 0x18);
    goto code_r0x8229f9a8;
  case 7:
    uVar1 = func_0x8229cf28(iVar2,*(undefined4 *)(iStack_70 + 0x18),0,0);
    goto code_r0x8229f9a8;
  case 8:
    uVar3 = func_0x8229cf28(iVar2,*(undefined4 *)(iStack_70 + 0x18),0,0);
    uVar1 = (ulonglong)(LZCOUNT(uVar3) << 0x20) >> 0x25;
code_r0x8229f9a8:
    func_0x8229dd78(iVar2,uVar1);
    break;
  case 9:
    func_0x8229c7e0(iVar2,*(undefined4 *)(iStack_70 + 0x18));
    break;
  case 10:
    func_0x8229c8a0(iVar2);
    break;
  case 0xb:
    func_0x8229de30(iVar2);
    break;
  case 0xc:
    func_0x8229dd78(iVar2,1);
    goto code_r0x8229fa34;
  case 0xd:
    func_0x8229c7e0(iVar2,1);
code_r0x8229fa34:
    func_0x822a77a0(*(undefined4 *)(iVar2 + 0x26c),0);
    break;
  case 0xe:
    func_0x8229ee60(iVar2);
    break;
  case 0xf:
  case 0x10:
  case 0x13:
  case 0x16:
  case 0x17:
  case 0x1a:
  case 0x1d:
  case 0x22:
  case 0x25:
  case 0x27:
  case 0x29:
  case 0x2b:
    iVar4 = iStack_70;
    break;
  case 0x11:
    *(undefined4 *)(iStack_70 + 0x10) = 2;
    uVar3 = func_0x8229e8f8(iVar2,*(undefined4 *)(iStack_70 + 0x18));
    *(undefined4 *)(iStack_70 + 0x18) = uVar3;
    iVar4 = iStack_70;
    break;
  case 0x12:
    *(undefined4 *)(iStack_70 + 0x10) = 2;
    uVar3 = func_0x8229cf28(iVar2,*(undefined4 *)(iStack_70 + 0x18),0,0);
    *(undefined4 *)(iStack_70 + 0x18) = uVar3;
    *(undefined4 *)(iVar2 + 0x58) = 1;
    iVar4 = iStack_70;
    break;
  case 0x14:
    iVar4 = *(int *)(iStack_70 + 0x18);
    goto code_r0x8229fac4;
  case 0x15:
    uVar8 = -*(int *)(iStack_70 + 0x18);
    goto code_r0x8229facc;
  case 0x18:
    uVar8 = *(int *)(iStack_6c + 0x18) * *(int *)(iStack_70 + 0x18);
    goto code_r0x8229facc;
  case 0x19:
    uVar8 = *(uint *)(iStack_6c + 0x18);
    if ((ulonglong)uVar8 == 0) {
      func_0x822a7180(iVar2 + 0x18,iVar2 + 0x278,0x5df,0xffffffff8202c0c8);
      *(undefined4 *)(iVar2 + 0x44) = 1;
      iVar4 = iStack_70;
    }
    else {
      trapWord(6,(ulonglong)uVar8,0);
      *(uint *)(iStack_70 + 0x18) = *(uint *)(iStack_70 + 0x18) / uVar8;
      iVar4 = iStack_70;
    }
    break;
  case 0x1b:
    uVar8 = *(int *)(iStack_6c + 0x18) + *(int *)(iStack_70 + 0x18);
    goto code_r0x8229fb5c;
  case 0x1c:
    uVar8 = *(int *)(iStack_70 + 0x18) - *(int *)(iStack_6c + 0x18);
    goto code_r0x8229facc;
  case 0x1e:
    bVar9 = *(uint *)(iStack_6c + 0x18) <= *(uint *)(iStack_70 + 0x18);
    goto code_r0x8229fb94;
  case 0x1f:
    bVar9 = *(uint *)(iStack_70 + 0x18) <= *(uint *)(iStack_6c + 0x18);
code_r0x8229fb94:
    uVar8 = -(uint)!bVar9 & 1;
    goto code_r0x8229facc;
  case 0x20:
    bVar9 = *(uint *)(iStack_70 + 0x18) <= *(uint *)(iStack_6c + 0x18);
    goto code_r0x8229fbcc;
  case 0x21:
    bVar9 = *(uint *)(iStack_6c + 0x18) <= *(uint *)(iStack_70 + 0x18);
code_r0x8229fbcc:
    uVar8 = (uint)bVar9;
code_r0x8229fb5c:
    *(uint *)(iStack_70 + 0x18) = uVar8;
    iVar4 = iStack_70;
    break;
  case 0x23:
    iVar4 = *(int *)(iStack_6c + 0x18) - *(int *)(iStack_70 + 0x18);
code_r0x8229fac4:
    uVar8 = (uint)LZCOUNT(iVar4) >> 5;
    goto code_r0x8229facc;
  case 0x24:
    uVar8 = (uint)LZCOUNT(*(int *)(iStack_6c + 0x18) - *(int *)(iStack_70 + 0x18)) >> 5 ^ 1;
    goto code_r0x8229facc;
  case 0x26:
    if ((*(int *)(iStack_70 + 0x18) == 0) || (uVar8 = 1, *(int *)(iStack_6c + 0x18) == 0)) {
      uVar8 = 0;
    }
    goto code_r0x8229facc;
  case 0x28:
    if ((*(int *)(iStack_70 + 0x18) != 0) || (uVar8 = 0, *(int *)(iStack_6c + 0x18) != 0)) {
      uVar8 = 1;
    }
    goto code_r0x8229facc;
  case 0x2a:
    if (*(int *)(iStack_70 + 0x18) == 0) {
      iStack_6c = iStack_68;
    }
    uVar8 = *(uint *)(iStack_6c + 0x18);
code_r0x8229facc:
    *(uint *)(iStack_70 + 0x18) = uVar8;
    iVar4 = iStack_70;
    break;
  case 0x2c:
  case 0x2d:
  case 0x2e:
    uVar1 = func_0x822cd240(0x30,0x10);
    if ((uVar1 & 0xffffffff) == 0) {
      iVar4 = 0;
    }
    else {
      iVar4 = func_0x822cd6f0(uVar1,iVar2 + 0x278);
    }
    func_0x8229d090(iVar2,iVar4);
  }
  if (*(int *)(iVar2 + 0x44) == 0) {
    iVar5 = *(int *)(iVar2 + 0x60);
    if (iVar5 == 0) {
      uVar1 = func_0x822cd240(0x14,0x10);
      if ((uVar1 & 0xffffffff) == 0) {
        iVar5 = 0;
      }
      else {
        iVar5 = func_0x822cd3a0(uVar1,iVar4,*(undefined4 *)(iVar2 + 0x5c),0xffffffff8202c0c0);
      }
      if (iVar5 == 0) {
        uVar6 = 0xffffffff8202c0a0;
LAB_8229f8cc:
        func_0x822a7180(iVar2 + 0x18,iVar2 + 0x278,0,uVar6);
        *(undefined4 *)(iVar2 + 0x44) = 1;
        halt_baddata();
      }
    }
    else {
      *(undefined4 *)(iVar2 + 0x60) = *(undefined4 *)(iVar5 + 0xc);
      *(int *)(iVar5 + 8) = iVar4;
      *(undefined4 *)(iVar5 + 0xc) = *(undefined4 *)(iVar2 + 0x5c);
    }
    *(int *)(iVar2 + 0x5c) = iVar5;
  }
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// ============================================================================
// Test 13: func @ 0x822abac0
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_13(undefined8 param_1,undefined4 param_2,ulonglong param_3)

{
  int iVar1;
  undefined4 *puVar3;
  undefined4 uVar4;
  ulonglong uVar2;
  int iVar5;
  undefined4 *puVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  longlong lVar9;
  longlong lVar10;
  ulonglong uVar11;
  double dVar12;
  int iStack_70;
  int iStack_6c;
  
  uVar2 = ZEXT48(&stack0x00000000);
  puVar3 = (undefined4 *)func_0x82487288();
  if (puVar3[0x14] != 0) {
    halt_baddata();
  }
  if ((param_3 & 0xffffffff) != 0) {
    lVar9 = (param_3 & 0x3fffffff) * 4 + (uVar2 - 0x70);
    uVar11 = param_3;
    do {
      iVar5 = puVar3[0xd];
      lVar9 = lVar9 + -4;
      if (iVar5 == 0) {
        func_0x822a7180(*puVar3,puVar3 + 4,0,0xffffffff8202c0f4);
        puVar3[0x13] = 1;
        halt_baddata();
      }
      uVar4 = *(undefined4 *)(iVar5 + 8);
      puVar3[0xd] = *(undefined4 *)(iVar5 + 0xc);
      *(undefined4 *)lVar9 = uVar4;
      *(undefined4 *)(iVar5 + 8) = 0;
      *(undefined4 *)(iVar5 + 0xc) = 0;
      uVar11 = uVar11 - 1;
    } while (uVar11 != 0);
  }
  iVar5 = 0;
  switch(param_2) {
  case 0:
  case 6:
    goto code_r0x822abbb4;
  case 1:
  case 2:
  case 4:
  case 5:
  case 10:
  case 0x17:
  case 0x19:
  case 0x1d:
  case 0x23:
  case 0x29:
  case 0x2a:
  case 0x2f:
  case 0x30:
    iVar5 = iStack_70;
    break;
  case 3:
    iVar5 = func_0x822cd338(iStack_6c,iStack_70);
    break;
  case 7:
    if (puVar3[0x1d] == 0) {
      puVar3[0x1d] = *(undefined4 *)(iStack_70 + 0x18);
    }
    goto code_r0x822abbb4;
  case 8:
    goto code_r0x822abbc4;
  case 9:
    if (((int)puVar3[0xe] < 6) || (9 < (int)puVar3[0xe])) {
      uVar7 = 0x7eb;
      uVar8 = 0xffffffff8202fa20;
      puVar6 = (undefined4 *)(iStack_70 + 0x10);
      iStack_6c = iStack_70;
      goto code_r0x822abc04;
    }
    *(undefined4 *)(iStack_70 + 0x54) = 1;
code_r0x822abbc4:
    func_0x822aa720(puVar3);
    iVar5 = iStack_70;
    break;
  case 0xb:
    iVar5 = puVar3[0xe];
    if (((1 < iVar5) && (iVar5 < 6)) || ((0xb < iVar5 && (iVar5 < 0x10)))) {
      *(int *)(iStack_6c + 0x40) = iStack_70;
      iVar5 = iStack_6c;
      break;
    }
    uVar7 = 0x7ec;
    uVar8 = 0xffffffff8202f9e0;
    puVar6 = (undefined4 *)(iStack_6c + 0x10);
    goto code_r0x822abc04;
  case 0xc:
  case 0xd:
  case 0xe:
  case 0xf:
  case 0x10:
  case 0x11:
  case 0x12:
  case 0x13:
  case 0x14:
    if (1 < (param_3 & 0xffffffff)) {
      *(int *)(iStack_70 + 0x3c) = iStack_6c;
    }
    iVar5 = iStack_70;
    if (2 < (param_3 & 0xffffffff)) {
      lVar10 = uVar2 - 0x68;
      puVar6 = (undefined4 *)(iStack_70 + 0x44);
      lVar9 = param_3 - 2;
      do {
        uVar4 = *(undefined4 *)lVar10;
        lVar9 = lVar9 + -1;
        *(undefined4 *)lVar10 = 0;
        lVar10 = lVar10 + 4;
        *puVar6 = uVar4;
        puVar6 = puVar6 + 1;
      } while (lVar9 != 0);
    }
    break;
  case 0x15:
  case 0x16:
    iVar5 = iStack_70;
    if (1 < (param_3 & 0xffffffff)) {
      lVar10 = uVar2 - 0x6c;
      puVar6 = (undefined4 *)(iStack_70 + 0x44);
      lVar9 = param_3 - 1;
      do {
        uVar4 = *(undefined4 *)lVar10;
        lVar9 = lVar9 + -1;
        *(undefined4 *)lVar10 = 0;
        lVar10 = lVar10 + 4;
        *puVar6 = uVar4;
        puVar6 = puVar6 + 1;
      } while (lVar9 != 0);
    }
    break;
  case 0x18:
    if (*(int *)(iStack_70 + 0x1c) == 0) {
      uVar4 = func_0x822a8dc0(puVar3,iStack_6c + 0x10);
      *(undefined4 *)(iStack_70 + 0x20) = uVar4;
      iVar5 = iStack_70;
    }
    else {
      func_0x822a7180(*puVar3,puVar3 + 4,0x7e6,0xffffffff8202f9b8);
      puVar3[0x13] = 1;
      *(undefined4 *)(iStack_70 + 0x20) = 0xf0000;
      iVar5 = iStack_70;
    }
    break;
  case 0x1a:
    if (*(int *)(iStack_70 + 0x14) == 0) {
      uVar4 = 0xd000000;
      iStack_6c = iStack_70;
      goto code_r0x822abd5c;
    }
    uVar7 = 0x7e2;
    uVar8 = 0xffffffff8202f990;
    iStack_6c = iStack_70;
    goto code_r0x822abe5c;
  case 0x1b:
    iVar1 = *(int *)(iStack_70 + 0x14);
    if (iVar1 == 0) {
      uVar4 = 0x1000000;
      iStack_6c = iStack_70;
    }
    else if (iVar1 == 0x2000000) {
      uVar4 = 0x3000000;
      iStack_6c = iStack_70;
    }
    else if (iVar1 == 0x4000000) {
      uVar4 = 0x5000000;
      iStack_6c = iStack_70;
    }
    else if (iVar1 == 0x7000000) {
      uVar4 = 0x8000000;
      iStack_6c = iStack_70;
    }
    else {
      if ((iVar1 == 0x9000000) || (iVar1 == 0xa000000)) {
        uVar7 = 0x7db;
        uVar8 = 0xffffffff8202f960;
        iStack_6c = iStack_70;
        goto code_r0x822abe5c;
      }
      iVar5 = iStack_70;
      if (iVar1 != 0xb000000) break;
      uVar4 = 0xc000000;
      iStack_6c = iStack_70;
    }
code_r0x822abd5c:
    *(undefined4 *)(iStack_6c + 0x14) = uVar4;
    iVar5 = iStack_6c;
    break;
  case 0x1c:
    if (*(int *)(iStack_70 + 0x18) == 1) {
      if (((int)puVar3[0xe] < 6) || (9 < (int)puVar3[0xe])) {
        uVar7 = 0x7ed;
        uVar8 = 0xffffffff8202f8dc;
      }
      else {
        if (*(int *)(iStack_6c + 0x14) == 0) {
          uVar4 = 0x6000000;
          goto code_r0x822abd5c;
        }
        uVar7 = 0x7dc;
        uVar8 = 0xffffffff8202f910;
      }
    }
    else {
      uVar7 = 0x7da;
      uVar8 = 0xffffffff8202f940;
    }
    goto code_r0x822abe5c;
  case 0x1e:
    if (*(int *)(iStack_70 + 0x1c) == 0) {
      uVar4 = func_0x822a8ed0(puVar3,iStack_6c + 0x10);
      *(undefined4 *)(iStack_70 + 0x24) = uVar4;
      iVar5 = iStack_70;
    }
    else {
      func_0x822a7180(*puVar3,puVar3 + 4,0x7e6,0xffffffff8202f8b8);
      puVar3[0x13] = 1;
      *(undefined4 *)(iStack_70 + 0x24) = 0xe40000;
      iVar5 = iStack_70;
    }
    break;
  case 0x21:
    iStack_6c = 0;
    goto code_r0x822abeb8;
  case 0x22:
code_r0x822abeb8:
    iVar5 = func_0x822a9e38(puVar3,iStack_70 + 0x10,iStack_6c);
    goto code_r0x822ac0bc;
  case 0x24:
    *(int *)(iStack_70 + 0x18) = *(int *)(iStack_6c + 0x18) + *(int *)(iStack_70 + 0x18);
    if (*(int *)(iStack_70 + 0x28) == 0) {
      *(undefined4 *)(iStack_70 + 0x28) = *(undefined4 *)(iStack_6c + 0x28);
      *(undefined4 *)(iStack_6c + 0x28) = 0;
      iVar5 = iStack_70;
      break;
    }
    iVar5 = iStack_70;
    if (*(int *)(iStack_6c + 0x28) == 0) break;
    uVar7 = 0x7d9;
    uVar8 = 0xffffffff8202f868;
    iStack_6c = iStack_70;
code_r0x822abe5c:
    puVar6 = puVar3 + 4;
code_r0x822abc04:
    func_0x822a7180(*puVar3,puVar6,uVar7,uVar8);
    puVar3[0x13] = 1;
    iVar5 = iStack_6c;
    break;
  case 0x25:
    uVar2 = func_0x822cd240(0x2c,0x10);
    if ((uVar2 & 0xffffffff) == 0) goto code_r0x822ac0b8;
    uVar4 = 0;
code_r0x822abf40:
    iVar5 = func_0x822d1318(uVar2,0,0,uVar4,0,iStack_70);
    goto code_r0x822ac0bc;
  case 0x26:
    uVar2 = func_0x822cd240(0x2c,0x10);
    if ((uVar2 & 0xffffffff) != 0) {
      uVar4 = *(undefined4 *)(iStack_70 + 0x18);
      iStack_70 = 0;
      goto code_r0x822abf40;
    }
    goto code_r0x822ac0b8;
  case 0x27:
    uVar2 = func_0x822cd240(0x30,0x10);
    if ((uVar2 & 0xffffffff) == 0) {
      iVar5 = 0;
    }
    else {
      iVar5 = func_0x822cd6f0(uVar2,puVar3 + 4);
    }
    func_0x822a8d48(puVar3,iVar5);
    *(undefined4 *)(iVar5 + 0x18) = 1;
    *(undefined4 *)(iVar5 + 0x10) = 2;
    break;
  case 0x28:
    uVar2 = func_0x822cd240(0x30,0x10);
    if ((uVar2 & 0xffffffff) == 0) {
      iVar5 = 0;
    }
    else {
      iVar5 = func_0x822cd6f0(uVar2,puVar3 + 4);
    }
    func_0x822a8d48(puVar3,iVar5);
    *(undefined4 *)(iVar5 + 0x18) = 0;
    *(undefined4 *)(iVar5 + 0x10) = 2;
    break;
  case 0x2b:
    *(int *)(iStack_70 + 0x18) = -*(int *)(iStack_70 + 0x18);
    iVar5 = iStack_70;
    break;
  case 0x2c:
  case 0x2d:
    *(undefined4 *)(iStack_70 + 0x10) = 5;
    dVar12 = (double)*(uint *)(iStack_70 + 0x18);
    goto code_r0x822ac030;
  case 0x2e:
    *(undefined4 *)(iStack_70 + 0x10) = 5;
    dVar12 = (double)*(uint *)(iStack_70 + 0x18);
    goto code_r0x822ac054;
  case 0x31:
    dVar12 = *(double *)(iStack_70 + 0x18);
code_r0x822ac054:
    dVar12 = -dVar12;
code_r0x822ac030:
    *(double *)(iStack_70 + 0x18) = dVar12;
    iVar5 = iStack_70;
    break;
  case 0x32:
  case 0x33:
  case 0x34:
  case 0x35:
  case 0x36:
  case 0x37:
  case 0x38:
  case 0x39:
  case 0x3a:
  case 0x3b:
  case 0x3c:
    uVar2 = func_0x822cd240(0x60,0x10);
    if ((uVar2 & 0xffffffff) != 0) {
      iVar5 = func_0x822d1218(uVar2,puVar3 + 4,puVar3[0x10],puVar3[0x11],puVar3[0x12]);
      goto code_r0x822ac0bc;
    }
    goto code_r0x822ac0b8;
  case 0x3d:
  case 0x3e:
  case 0x3f:
    uVar2 = func_0x822cd240(0x30,0x10);
    if ((uVar2 & 0xffffffff) != 0) {
      iVar5 = func_0x822cd6f0(uVar2,puVar3 + 4);
      goto code_r0x822ac0bc;
    }
code_r0x822ac0b8:
    iVar5 = 0;
code_r0x822ac0bc:
    func_0x822a8d48(puVar3,iVar5);
  }
LAB_822ac0c8:
  if (puVar3[0x14] == 0) {
    uVar2 = func_0x822cd240(0x14,0x10);
    if ((uVar2 & 0xffffffff) == 0) {
      iVar5 = 0;
    }
    else {
      iVar5 = func_0x822cd3a0(uVar2,iVar5,puVar3[0xd],0xffffffff8202c0c0);
    }
    if (iVar5 == 0) {
      func_0x822a7180(*puVar3,puVar3 + 4,0,0xffffffff8202c0a0);
      puVar3[0x14] = 1;
      puVar3[0x13] = 1;
    }
    else {
      puVar3[0xd] = iVar5;
    }
  }
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
code_r0x822abbb4:
  iVar5 = 0;
  goto LAB_822ac0c8;
}



// ============================================================================
// Test 14: func @ 0x823f7400
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_14(undefined8 param_1,int param_2)

{
  int iVar4;
  longlong lVar1;
  undefined8 uVar2;
  uint *puVar5;
  longlong lVar3;
  undefined4 *puVar6;
  undefined1 *puVar7;
  double dVar8;
  undefined1 auStack_150 [4];
  undefined1 auStack_14c [4];
  undefined1 auStack_148 [4];
  undefined1 auStack_144 [4];
  undefined1 auStack_140 [4];
  undefined1 auStack_13c [4];
  undefined1 auStack_138 [4];
  undefined1 auStack_134 [4];
  undefined1 auStack_130 [4];
  undefined1 auStack_12c [4];
  undefined1 auStack_128 [4];
  undefined1 auStack_124 [4];
  undefined1 auStack_120 [4];
  undefined1 auStack_11c [4];
  undefined1 auStack_118 [4];
  undefined1 auStack_114 [4];
  undefined1 auStack_110 [4];
  undefined1 auStack_10c [4];
  undefined1 auStack_108 [4];
  undefined1 auStack_104 [4];
  undefined1 auStack_100 [8];
  undefined1 auStack_f8 [4];
  int iStack_f4;
  undefined1 auStack_f0 [4];
  int iStack_ec;
  undefined1 auStack_e8 [4];
  int iStack_e4;
  undefined1 auStack_e0 [8];
  undefined1 auStack_d8 [4];
  int iStack_d4;
  undefined1 auStack_d0 [4];
  int iStack_cc;
  undefined1 auStack_c8 [4];
  int iStack_c4;
  undefined1 auStack_c0 [4];
  int iStack_bc;
  undefined1 auStack_b8 [4];
  int iStack_b4;
  undefined1 auStack_b0 [4];
  int iStack_ac;
  undefined1 auStack_a8 [4];
  int iStack_a4;
  undefined1 auStack_a0 [4];
  int iStack_9c;
  undefined1 auStack_98 [4];
  int iStack_94;
  undefined1 auStack_90 [4];
  int iStack_8c;
  undefined1 auStack_88 [4];
  int iStack_84;
  undefined1 auStack_80 [4];
  int iStack_7c;
  undefined1 auStack_78 [4];
  int iStack_74;
  undefined1 auStack_70 [4];
  int iStack_6c;
  undefined1 auStack_68 [4];
  int iStack_64;
  undefined1 auStack_60 [4];
  int iStack_5c;
  undefined1 auStack_58 [4];
  int iStack_54;
  undefined1 auStack_50 [4];
  int iStack_4c;
  undefined1 auStack_48 [4];
  int iStack_44;
  
  iVar4 = func_0x831a8160();
  lVar1 = func_0x83154600();
  func_0x82df3a08(auStack_14c,uRam83267658);
  uVar2 = func_0x823053e8(lVar1);
  dVar8 = (double)fRam820008a4;
  func_0x82bb2cb8(dVar8,auStack_f8,uVar2,auStack_14c);
  if (iStack_f4 != 0) {
    func_0x822c0890();
  }
  func_0x82df3428(auStack_14c);
  func_0x82df3a08(auStack_14c,uRam83267c74);
  uVar2 = func_0x823053e8(lVar1);
  func_0x82bb2cb8(dVar8,auStack_70,uVar2,auStack_14c);
  if (iStack_6c != 0) {
    func_0x822c0890();
  }
  func_0x82df3428(auStack_14c);
  uVar2 = func_0x82a13598(lVar1);
  puVar5 = (uint *)func_0x8250f4c8(auStack_e0,uVar2);
  lVar3 = (ulonglong)*puVar5 - 4;
  if ((ulonglong)*puVar5 == 0) {
    lVar3 = 0;
  }
  puVar6 = (undefined4 *)func_0x82508528(lVar3);
  func_0x82e3ff08(auStack_150,*puVar6);
  func_0x82df1c90(auStack_e0);
  switch(*(undefined4 *)(param_2 + 0x18)) {
  case 0:
    func_0x82df3a08(auStack_14c,uRam83267658);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_90,uVar2,auStack_14c);
    if (iStack_8c != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_14c;
    break;
  case 1:
    func_0x82df3a08(auStack_124,uRam83267c74);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_d0,uVar2,auStack_124);
    if (iStack_cc != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_124;
    break;
  case 2:
    *(undefined1 *)(iVar4 + 0x71) = 1;
    func_0x82df3878(lVar1 + 0x2e8,uRam83267c8c);
    func_0x82df3a08(auStack_104,uRam83267c8c);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_50,uVar2,auStack_104);
    if (iStack_4c != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_104);
    func_0x82df3a08(auStack_13c,0xffffffff82023334);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_c0,auStack_150,auStack_13c,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3c8) = *puVar6;
    func_0x822c4460(iVar4 + 0x3cc,puVar6 + 1);
    if (iStack_bc != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_13c);
    func_0x82df3a08(auStack_11c,0xffffffff82023318);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_80,auStack_150,auStack_11c,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3dc) = *puVar6;
    func_0x822c4460(iVar4 + 0x3e0,puVar6 + 1);
    if (iStack_7c != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_11c;
    break;
  case 3:
    *(undefined1 *)(iVar4 + 0x71) = 1;
    func_0x82df3878(lVar1 + 0x2e8,uRam83267c78);
    func_0x82df3a08(auStack_134,uRam83267c78);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_b0,uVar2,auStack_134);
    if (iStack_ac != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_134);
    func_0x82df3a08(auStack_10c,0xffffffff820232fc);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_60,auStack_150,auStack_10c,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3c8) = *puVar6;
    func_0x822c4460(iVar4 + 0x3cc,puVar6 + 1);
    if (iStack_5c != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_10c);
    func_0x82df3a08(auStack_12c,0xffffffff820232e0);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_a0,auStack_150,auStack_12c,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3dc) = *puVar6;
    func_0x822c4460(iVar4 + 0x3e0,puVar6 + 1);
    if (iStack_9c != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_12c;
    break;
  case 4:
    *(undefined1 *)(iVar4 + 0x71) = 1;
    func_0x82df3878(lVar1 + 0x2e8,uRam83267c7c);
    func_0x82df3a08(auStack_114,uRam83267c7c);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_f0,uVar2,auStack_114);
    if (iStack_ec != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_114);
    func_0x82df3a08(auStack_148,0xffffffff820232c4);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_e8,auStack_150,auStack_148,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3c8) = *puVar6;
    func_0x822c4460(iVar4 + 0x3cc,puVar6 + 1);
    if (iStack_e4 != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_148);
    func_0x82df3a08(auStack_144,0xffffffff820232a8);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_d8,auStack_150,auStack_144,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3dc) = *puVar6;
    func_0x822c4460(iVar4 + 0x3e0,puVar6 + 1);
    if (iStack_d4 != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_144;
    break;
  case 5:
    *(undefined1 *)(iVar4 + 0x71) = 1;
    func_0x82df3878(lVar1 + 0x2e8,uRam83267c80);
    func_0x82df3a08(auStack_140,uRam83267c80);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_c8,uVar2,auStack_140);
    if (iStack_c4 != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_140);
    func_0x82df3a08(auStack_138,0xffffffff8202328c);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_b8,auStack_150,auStack_138,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3c8) = *puVar6;
    func_0x822c4460(iVar4 + 0x3cc,puVar6 + 1);
    if (iStack_b4 != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_138);
    func_0x82df3a08(auStack_130,0xffffffff82023270);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_a8,auStack_150,auStack_130,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3dc) = *puVar6;
    func_0x822c4460(iVar4 + 0x3e0,puVar6 + 1);
    if (iStack_a4 != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_130;
    break;
  case 6:
    *(undefined1 *)(iVar4 + 0x71) = 1;
    func_0x82df3878(lVar1 + 0x2e8,uRam83267c84);
    func_0x82df3a08(auStack_128,uRam83267c84);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_98,uVar2,auStack_128);
    if (iStack_94 != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_128);
    func_0x82df3a08(auStack_120,0xffffffff82023254);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_88,auStack_150,auStack_120,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3c8) = *puVar6;
    func_0x822c4460(iVar4 + 0x3cc,puVar6 + 1);
    if (iStack_84 != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_120);
    func_0x82df3a08(auStack_118,0xffffffff82023238);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_78,auStack_150,auStack_118,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3dc) = *puVar6;
    func_0x822c4460(iVar4 + 0x3e0,puVar6 + 1);
    if (iStack_74 != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_118;
    break;
  case 7:
    *(undefined1 *)(iVar4 + 0x71) = 1;
    func_0x82df3878(lVar1 + 0x2e8,uRam83267c88);
    func_0x82df3a08(auStack_110,uRam83267c88);
    uVar2 = func_0x823053e8(lVar1);
    func_0x82bb2c20(dVar8,auStack_68,uVar2,auStack_110);
    if (iStack_64 != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_110);
    func_0x82df3a08(auStack_108,0xffffffff8202321c);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_58,auStack_150,auStack_108,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3c8) = *puVar6;
    func_0x822c4460(iVar4 + 0x3cc,puVar6 + 1);
    if (iStack_54 != 0) {
      func_0x822c0890();
    }
    func_0x82df3428(auStack_108);
    func_0x82df3a08(auStack_100,0xffffffff82023200);
    puVar6 = (undefined4 *)func_0x82e40a68(auStack_48,auStack_150,auStack_100,0);
    iVar4 = func_0x82a13598(lVar1);
    *(undefined4 *)(iVar4 + 0x3dc) = *puVar6;
    func_0x822c4460(iVar4 + 0x3e0,puVar6 + 1);
    if (iStack_44 != 0) {
      func_0x822c0890();
    }
    puVar7 = auStack_100;
    break;
  default:
    goto LAB_823f7c80;
  }
  func_0x82df3428(puVar7);
LAB_823f7c80:
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// ============================================================================
// Test 15: func @ 0x826a4e98
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_15(undefined8 param_1,undefined8 param_2)

{
  int iVar1;
  undefined1 *puVar2;
  undefined1 auStack_150 [4];
  undefined1 auStack_14c [4];
  undefined1 auStack_148 [4];
  undefined1 auStack_144 [4];
  undefined1 auStack_140 [4];
  undefined1 auStack_13c [4];
  undefined1 auStack_138 [4];
  undefined1 auStack_134 [4];
  undefined1 auStack_130 [4];
  undefined1 auStack_12c [4];
  undefined1 auStack_128 [4];
  undefined1 auStack_124 [4];
  undefined1 auStack_120 [4];
  undefined1 auStack_11c [4];
  undefined1 auStack_118 [4];
  undefined1 auStack_114 [4];
  undefined1 auStack_110 [4];
  undefined1 auStack_10c [4];
  undefined1 auStack_108 [4];
  undefined1 auStack_104 [4];
  undefined1 auStack_100 [4];
  undefined1 auStack_fc [4];
  undefined1 auStack_f8 [4];
  undefined1 auStack_f4 [4];
  undefined1 auStack_f0 [4];
  undefined1 auStack_ec [4];
  undefined1 auStack_e8 [4];
  undefined1 auStack_e4 [4];
  undefined1 auStack_e0 [4];
  undefined1 auStack_dc [4];
  undefined1 auStack_d8 [4];
  undefined1 auStack_d4 [4];
  undefined1 auStack_d0 [4];
  undefined1 auStack_cc [4];
  undefined1 auStack_c8 [4];
  undefined1 auStack_c4 [4];
  undefined1 auStack_c0 [4];
  undefined1 auStack_bc [4];
  undefined1 auStack_b8 [4];
  undefined1 auStack_b4 [4];
  undefined1 auStack_b0 [4];
  undefined1 auStack_ac [4];
  undefined1 auStack_a8 [4];
  undefined1 auStack_a4 [4];
  undefined1 auStack_a0 [4];
  undefined1 auStack_9c [4];
  undefined1 auStack_98 [4];
  undefined1 auStack_94 [4];
  undefined1 auStack_90 [4];
  undefined1 auStack_8c [4];
  undefined1 auStack_88 [4];
  undefined1 auStack_84 [4];
  undefined1 auStack_80 [128];
  
  iVar1 = func_0x831a8144();
  func_0x82df3a08(auStack_150,0xffffffff82024a98);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff8204132c);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff82041310);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff8203fd08);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff82044370);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff8204d2d0);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff82051160);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff82051154);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff8204d2e8);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff8205114c);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff8205113c);
  func_0x825a1588(param_2,auStack_150,0);
  func_0x82df3428(auStack_150);
  func_0x82df3a08(auStack_150,0xffffffff82024a98);
  func_0x825a1588(param_2,auStack_150,1);
  func_0x82df3428(auStack_150);
  switch(*(undefined4 *)(iVar1 + 100)) {
  case 1:
    func_0x82df3a08(auStack_150,0xffffffff8204132c);
    func_0x825a1588(param_2,auStack_150,1);
    func_0x82df3428(auStack_150);
    func_0x82df3a08(auStack_e4,0xffffffff82041310);
    func_0x825a1588(param_2,auStack_e4,1);
    func_0x82df3428(auStack_e4);
    func_0x82df3a08(auStack_144,0xffffffff82044370);
    func_0x825a1588(param_2,auStack_144,1);
    func_0x82df3428(auStack_144);
    func_0x82df3a08(auStack_8c,0xffffffff8204d2d0);
    func_0x825a1588(param_2,auStack_8c,1);
    func_0x82df3428(auStack_8c);
    func_0x82df3a08(auStack_13c,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_13c,1);
    func_0x82df3428(auStack_13c);
    func_0x82df3a08(auStack_dc,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_dc,1);
    puVar2 = auStack_dc;
    break;
  case 2:
    func_0x82df3a08(auStack_134,0xffffffff8204132c);
    func_0x825a1588(param_2,auStack_134,1);
    func_0x82df3428(auStack_134);
    func_0x82df3a08(auStack_ac,0xffffffff82041310);
    func_0x825a1588(param_2,auStack_ac,1);
    func_0x82df3428(auStack_ac);
    func_0x82df3a08(auStack_12c,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_12c,1);
    func_0x82df3428(auStack_12c);
    func_0x82df3a08(auStack_d4,0xffffffff8204d2d0);
    func_0x825a1588(param_2,auStack_d4,1);
    func_0x82df3428(auStack_d4);
    func_0x82df3a08(auStack_124,0xffffffff82051154);
    func_0x825a1588(param_2,auStack_124,1);
    func_0x82df3428(auStack_124);
    func_0x82df3a08(auStack_94,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_94,1);
    func_0x82df3428(auStack_94);
    func_0x82df3a08(auStack_11c,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_11c,1);
    puVar2 = auStack_11c;
    break;
  case 3:
    func_0x82df3a08(auStack_cc,0xffffffff8204132c);
    func_0x825a1588(param_2,auStack_cc,1);
    func_0x82df3428(auStack_cc);
    func_0x82df3a08(auStack_114,0xffffffff82041310);
    func_0x825a1588(param_2,auStack_114,1);
    func_0x82df3428(auStack_114);
    func_0x82df3a08(auStack_a4,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_a4,1);
    func_0x82df3428(auStack_a4);
    func_0x82df3a08(auStack_10c,0xffffffff8204d2d0);
    func_0x825a1588(param_2,auStack_10c,1);
    func_0x82df3428(auStack_10c);
    func_0x82df3a08(auStack_c4,0xffffffff82051154);
    func_0x825a1588(param_2,auStack_c4,1);
    func_0x82df3428(auStack_c4);
    func_0x82df3a08(auStack_104,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_104,1);
    func_0x82df3428(auStack_104);
    func_0x82df3a08(auStack_84,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_84,1);
    puVar2 = auStack_84;
    break;
  case 4:
    func_0x82df3a08(auStack_fc,0xffffffff8204132c);
    func_0x825a1588(param_2,auStack_fc,1);
    func_0x82df3428(auStack_fc);
    func_0x82df3a08(auStack_bc,0xffffffff82041310);
    func_0x825a1588(param_2,auStack_bc,1);
    func_0x82df3428(auStack_bc);
    func_0x82df3a08(auStack_f4,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_f4,1);
    func_0x82df3428(auStack_f4);
    func_0x82df3a08(auStack_9c,0xffffffff82044370);
    func_0x825a1588(param_2,auStack_9c,1);
    func_0x82df3428(auStack_9c);
    func_0x82df3a08(auStack_ec,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_ec,1);
    func_0x82df3428(auStack_ec);
    func_0x82df3a08(auStack_b4,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_b4,1);
    puVar2 = auStack_b4;
    break;
  case 5:
    func_0x82df3a08(auStack_14c,0xffffffff8204132c);
    func_0x825a1588(param_2,auStack_14c,1);
    func_0x82df3428(auStack_14c);
    func_0x82df3a08(auStack_148,0xffffffff82041310);
    func_0x825a1588(param_2,auStack_148,1);
    func_0x82df3428(auStack_148);
    func_0x82df3a08(auStack_140,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_140,1);
    func_0x82df3428(auStack_140);
    func_0x82df3a08(auStack_138,0xffffffff82051154);
    func_0x825a1588(param_2,auStack_138,1);
    func_0x82df3428(auStack_138);
    func_0x82df3a08(auStack_130,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_130,1);
    func_0x82df3428(auStack_130);
    func_0x82df3a08(auStack_128,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_128,1);
    puVar2 = auStack_128;
    break;
  case 6:
    func_0x82df3a08(auStack_120,0xffffffff8204132c);
    func_0x825a1588(param_2,auStack_120,1);
    func_0x82df3428(auStack_120);
    func_0x82df3a08(auStack_118,0xffffffff82041310);
    func_0x825a1588(param_2,auStack_118,1);
    func_0x82df3428(auStack_118);
    func_0x82df3a08(auStack_110,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_110,1);
    func_0x82df3428(auStack_110);
    func_0x82df3a08(auStack_108,0xffffffff82051154);
    func_0x825a1588(param_2,auStack_108,1);
    func_0x82df3428(auStack_108);
    func_0x82df3a08(auStack_100,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_100,1);
    func_0x82df3428(auStack_100);
    func_0x82df3a08(auStack_f8,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_f8,1);
    puVar2 = auStack_f8;
    break;
  case 7:
    func_0x82df3a08(auStack_f0,0xffffffff82044370);
    func_0x825a1588(param_2,auStack_f0,1);
    func_0x82df3428(auStack_f0);
    func_0x82df3a08(auStack_e8,0xffffffff82051160);
    func_0x825a1588(param_2,auStack_e8,1);
    func_0x82df3428(auStack_e8);
    func_0x82df3a08(auStack_e0,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_e0,1);
    func_0x82df3428(auStack_e0);
    func_0x82df3a08(auStack_d8,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_d8,1);
    func_0x82df3428(auStack_d8);
    if (*(char *)(iVar1 + 0x84) == '\0') {
      halt_baddata();
    }
    func_0x82df3a08(auStack_d0,0xffffffff82051154);
    func_0x825a1588(param_2,auStack_d0,1);
    puVar2 = auStack_d0;
    break;
  case 8:
    func_0x82df3a08(auStack_c8,0xffffffff82051154);
    func_0x825a1588(param_2,auStack_c8,1);
    func_0x82df3428(auStack_c8);
    func_0x82df3a08(auStack_c0,0xffffffff82051160);
    func_0x825a1588(param_2,auStack_c0,1);
    func_0x82df3428(auStack_c0);
    func_0x82df3a08(auStack_b8,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_b8,1);
    func_0x82df3428(auStack_b8);
    func_0x82df3a08(auStack_b0,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_b0,1);
    puVar2 = auStack_b0;
    break;
  case 9:
    func_0x82df3a08(auStack_a8,0xffffffff82051154);
    func_0x825a1588(param_2,auStack_a8,1);
    func_0x82df3428(auStack_a8);
    func_0x82df3a08(auStack_a0,0xffffffff82051160);
    func_0x825a1588(param_2,auStack_a0,1);
    func_0x82df3428(auStack_a0);
    func_0x82df3a08(auStack_98,0xffffffff8204d2e8);
    func_0x825a1588(param_2,auStack_98,1);
    func_0x82df3428(auStack_98);
    func_0x82df3a08(auStack_90,0xffffffff8203fd08);
    func_0x825a1588(param_2,auStack_90,1);
    puVar2 = auStack_90;
    break;
  case 10:
    func_0x82df3a08(auStack_88,0xffffffff8205114c);
    func_0x825a1588(param_2,auStack_88,1);
    func_0x82df3428(auStack_88);
    func_0x82df3a08(auStack_80,0xffffffff8205113c);
    func_0x825a1588(param_2,auStack_80,1);
    puVar2 = auStack_80;
    break;
  default:
    goto LAB_831a8194;
  }
  func_0x82df3428(puVar2);
LAB_831a8194:
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// ============================================================================
// Test 16: func @ 0x824ce490
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Type propagation algorithm not settling */

void test_16(undefined8 param_1,uint *param_2,uint *param_3)

{
  uint uVar1;
  int iVar2;
  uint uVar3;
  
  iVar2 = func_0x82696f38();
  func_0x82960c04(0xffffffff8297d2d4);
  if (0x1000 < iVar2) {
    if (iVar2 - 0x1003U < 8) {
      if (iVar2 == 0x1004) {
        if (3 < *param_3) {
          uVar3 = (uint)uRam8297d280;
          goto LAB_824ce510;
        }
      }
      else if (iVar2 == 0x1005) {
        if (3 < *param_3) {
          uVar3 = (uint)uRam8297d282;
          goto LAB_824ce510;
        }
      }
      else {
        if (iVar2 != 0x1006) {
          if (iVar2 == 0x1007) {
            uVar1 = *param_3;
            uVar3 = uRam8297d2ac;
          }
          else if (iVar2 == 0x1008) {
            uVar1 = *param_3;
            uVar3 = uRam8297d2c8;
          }
          else if (iVar2 == 0x1009) {
            uVar1 = *param_3;
            uVar3 = uRam8297d28c;
          }
          else if (iVar2 == 0x1003) {
            uVar1 = *param_3;
            uVar3 = uRam8297d278;
          }
          else {
            uVar1 = *param_3;
            uVar3 = uRam8297d290;
          }
          goto joined_r0x824ce8c8;
        }
        if (3 < *param_3) {
          uVar3 = (uint)uRam8297d284;
          goto LAB_824ce510;
        }
      }
      goto LAB_824ce524;
    }
LAB_824ce930:
    goto LAB_824ce938;
  }
  if (iVar2 == 0x1000) {
    uVar1 = *param_3;
    uVar3 = uRam8297d2a8;
    goto joined_r0x824ce8c8;
  }
  switch(iVar2 + -1) {
  case 0:
    uVar1 = *param_3;
    uVar3 = uRam8297d294;
    break;
  case 1:
    uVar1 = *param_3;
    uVar3 = uRam8297d298;
    goto joined_r0x824ce8c8;
  case 2:
    uVar1 = *param_3;
    uVar3 = uRam8297d29c;
joined_r0x824ce8c8:
    if (uVar1 < 4) goto LAB_824ce524;
    goto LAB_824ce510;
  case 3:
    uVar1 = *param_3;
    uVar3 = uRam8297d248;
    break;
  case 4:
    uVar1 = *param_3;
    uVar3 = uRam8297d2a0;
    break;
  case 5:
    uVar1 = *param_3;
    uVar3 = uRam8297d2a4;
    break;
  case 6:
    uVar1 = *param_3;
    uVar3 = uRam8297d2b0;
    break;
  case 7:
    uVar1 = *param_3;
    uVar3 = uRam8297d2b4;
    break;
  case 8:
    uVar1 = *param_3;
    uVar3 = uRam8297d254;
    break;
  case 9:
    if (*param_3 < 4) goto LAB_824ce524;
    uVar3 = (uint)uRam8297d2bc;
    goto LAB_824ce510;
  case 10:
    if (3 < *param_3) {
      uVar3 = (uint)uRam8297d2be;
      goto LAB_824ce510;
    }
    goto LAB_824ce524;
  case 0xb:
    if (3 < *param_3) {
      uVar3 = (uint)uRam8297d2c0;
      goto LAB_824ce510;
    }
    goto LAB_824ce524;
  case 0xc:
    if (3 < *param_3) {
      uVar3 = (uint)uRam8297d2c2;
      goto LAB_824ce510;
    }
    goto LAB_824ce524;
  case 0xd:
    uVar1 = *param_3;
    uVar3 = uRam8297d258;
    break;
  case 0xe:
    uVar1 = *param_3;
    uVar3 = uRam8297d2b8;
    break;
  case 0xf:
    uVar1 = *param_3;
    uVar3 = uRam8297d260;
    break;
  case 0x10:
    uVar1 = *param_3;
    uVar3 = uRam8297d264;
    break;
  case 0x11:
    uVar1 = *param_3;
    uVar3 = uRam8297d24c;
    break;
  case 0x12:
    uVar1 = *param_3;
    uVar3 = uRam8297d250;
    break;
  case 0x13:
    uVar1 = *param_3;
    uVar3 = uRam8297d268;
    break;
  case 0x14:
    uVar1 = *param_3;
    uVar3 = uRam8297d2c4;
    break;
  case 0x15:
    uVar1 = *param_3;
    uVar3 = uRam8297d25c;
    break;
  case 0x16:
    uVar1 = *param_3;
    uVar3 = uRam8297d26c;
    break;
  case 0x17:
    uVar1 = *param_3;
    uVar3 = uRam8297d270;
    break;
  case 0x18:
    uVar1 = *param_3;
    uVar3 = uRam8297d274;
    break;
  default:
    goto LAB_824ce930;
  case 0x1a:
    uVar1 = *param_3;
    uVar3 = uRam8297d27c;
    break;
  case 0x1b:
    uVar1 = *param_3;
    uVar3 = uRam8297d288;
  }
  if (3 < uVar1) {
LAB_824ce510:
    *param_2 = uVar3;
  }
LAB_824ce524:
  *param_3 = 4;
LAB_824ce938:
  func_0x82960c14(0xffffffff8297d2d4);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// ============================================================================
// Test 17: func @ 0x826478d8
// ============================================================================


undefined4 * test_17(undefined4 param_1)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  
  switch(param_1) {
  case 0:
    puVar1 = (undefined4 *)func_0x822c4330(0x20,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    puVar1[4] = 0;
    *puVar1 = 0x820985bc;
    puVar1[5] = 0;
    puVar1[6] = 0x14;
    puVar1[7] = 0x14;
    puVar1[3] = 0;
    return puVar1;
  case 1:
    puVar1 = (undefined4 *)func_0x822c4330(0x20,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x820985d0;
    uVar2 = 1;
    goto code_r0x82647f8c;
  case 2:
    puVar1 = (undefined4 *)func_0x822c4330(0x20,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x820985e4;
    uVar2 = 2;
    goto code_r0x82647f8c;
  case 3:
    puVar1 = (undefined4 *)func_0x822c4330(0x24,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x820985f8;
    uVar2 = 3;
    goto code_r0x82647a00;
  case 4:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x8209860c;
    puVar1[1] = 0xff7fffff;
    uVar2 = 4;
    puVar1[2] = 0xff7fffff;
    break;
  case 5:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098620;
    puVar1[1] = 0xff7fffff;
    uVar2 = 5;
    puVar1[2] = 0xff7fffff;
    break;
  case 6:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098698;
    puVar1[1] = 0xff7fffff;
    uVar2 = 6;
    puVar1[2] = 0xff7fffff;
    break;
  case 7:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x820986ac;
    puVar1[1] = 0xff7fffff;
    uVar2 = 7;
    puVar1[2] = 0xff7fffff;
    break;
  case 8:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x820986c0;
    puVar1[1] = 0xff7fffff;
    uVar2 = 8;
    puVar1[2] = 0xff7fffff;
    break;
  case 9:
    puVar1 = (undefined4 *)func_0x822c4330(0x24,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x82098710;
    uVar2 = 9;
    goto code_r0x82647a00;
  case 10:
    puVar1 = (undefined4 *)func_0x822c4330(0x24,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x82098724;
    uVar2 = 10;
code_r0x82647a00:
    puVar1[8] = 0x14;
    goto code_r0x82647f8c;
  case 0xb:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098738;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0xb;
    puVar1[2] = 0xff7fffff;
    break;
  case 0xc:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x8209874c;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0xc;
    puVar1[2] = 0xff7fffff;
    break;
  case 0xd:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098760;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0xd;
    puVar1[2] = 0xff7fffff;
    break;
  case 0xe:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098774;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0xe;
    puVar1[2] = 0xff7fffff;
    break;
  case 0xf:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098788;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0xf;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x10:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x8209879c;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x10;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x11:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x820987b0;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x11;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x12:
    puVar1 = (undefined4 *)func_0x822c4330(0x20,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x820987c4;
    uVar2 = 0x12;
    goto code_r0x82647f8c;
  case 0x13:
    puVar1 = (undefined4 *)func_0x822c4330(0x20,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x820987d8;
    uVar2 = 0x13;
    goto code_r0x82647f8c;
  case 0x14:
    puVar1 = (undefined4 *)func_0x822c4330(0x20,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    puVar1[4] = 0;
    puVar1[5] = 0;
    *puVar1 = 0x820987ec;
    puVar1[6] = 0x14;
    puVar1[7] = 0x14;
    puVar1[3] = 0x14;
    return puVar1;
  case 0x15:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x820986d4;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x15;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x16:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x820986e8;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x16;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x17:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x820986fc;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x17;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x18:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098634;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x18;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x19:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098648;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x19;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x1a:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x8209865c;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x1a;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x1b:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098670;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x1b;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x1c:
    puVar1 = (undefined4 *)func_0x822c4330(0x1c,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    uVar3 = 0x82098684;
    puVar1[1] = 0xff7fffff;
    uVar2 = 0x1c;
    puVar1[2] = 0xff7fffff;
    break;
  case 0x1d:
    puVar1 = (undefined4 *)func_0x822c4330(0x20,0x209c0000);
    if (puVar1 == (undefined4 *)0x0) {
      return (undefined4 *)0x0;
    }
    puVar1[1] = 0xff7fffff;
    puVar1[2] = 0xff7fffff;
    uVar3 = 0x82098800;
    uVar2 = 0x1d;
code_r0x82647f8c:
    puVar1[4] = 0;
    puVar1[5] = 0;
    *puVar1 = uVar3;
    puVar1[6] = 0x14;
    puVar1[7] = 0x14;
    goto code_r0x82647fa4;
  default:
    return (undefined4 *)0x0;
  }
  puVar1[4] = 0;
  puVar1[5] = 0;
  *puVar1 = uVar3;
  puVar1[6] = 0x14;
code_r0x82647fa4:
  puVar1[3] = uVar2;
  return puVar1;
}



// ============================================================================
// Test 18: func @ 0x825ec718
// ============================================================================


/* WARNING: Control flow encountered bad instruction data */

void test_18(undefined8 param_1,undefined8 param_2,longlong param_3)

{
  byte bVar1;
  byte bVar2;
  uint *puVar4;
  longlong lVar3;
  uint uVar5;
  int *piVar6;
  uint uVar7;
  undefined4 uVar8;
  uint uVar10;
  uint uVar11;
  ulonglong uVar9;
  uint uVar12;
  int iVar13;
  uint uVar14;
  ulonglong uVar15;
  uint uVar16;
  byte *pbVar17;
  undefined4 uStack_b0;
  undefined4 uStack_ac;
  undefined4 uStack_a8;
  undefined4 uStack_a4;
  undefined4 uStack_a0;
  undefined4 uStack_9c;
  undefined4 uStack_98;
  undefined4 auStack_94 [37];
  
  puVar4 = (uint *)func_0x8258dfb8();
  uVar14 = puVar4[0xd];
  piVar6 = (int *)param_2;
  pbVar17 = (byte *)*piVar6;
  uVar12 = piVar6[1];
  uVar10 = puVar4[8];
  uVar15 = (ulonglong)uVar10;
  uVar16 = puVar4[7];
  if (uVar14 < puVar4[0xc]) {
    uVar5 = (puVar4[0xc] - uVar14) - 1;
  }
  else {
    uVar5 = puVar4[0xb] - uVar14;
  }
  uVar11 = *puVar4;
  while (uVar11 < 10) {
    uVar10 = (uint)uVar15;
    switch(uVar11) {
    case 0:
      for (; uVar10 = (uint)uVar15, uVar16 < 3; uVar16 = uVar16 + 8) {
        if (uVar12 == 0) goto code_r0x825ece94;
        bVar1 = *pbVar17;
        param_3 = 0;
        uVar12 = uVar12 - 1;
        pbVar17 = pbVar17 + 1;
        uVar15 = (uint)bVar1 << (uVar16 & 0x3f) | uVar15;
      }
      uVar9 = ((uVar15 & 7) << 0x20) >> 0x21;
      puVar4[6] = (uint)(uVar15 & 7) & 1;
      if (uVar9 == 0) {
        *puVar4 = 1;
        uVar11 = uVar16 - 3 & 7;
        uVar16 = (uVar16 - 3) - uVar11;
        uVar15 = (ulonglong)((uVar10 >> 3) >> uVar11);
      }
      else if (uVar9 == 1) {
        func_0x825f06b8(&uStack_9c,&uStack_a0,&uStack_a4,&uStack_a8,param_2);
        uVar11 = func_0x825ef8e8(uStack_9c,uStack_a0,uStack_a4,uStack_a8,param_2);
        puVar4[1] = uVar11;
        if (uVar11 == 0) goto code_r0x825ecea8;
        uVar15 = (uVar15 << 0x20) >> 0x23;
        *puVar4 = 6;
        uVar16 = uVar16 - 3;
      }
      else {
        if (uVar9 < 3) {
          uVar15 = (uVar15 << 0x20) >> 0x23;
          uVar16 = uVar16 - 3;
          uVar10 = 3;
          goto code_r0x825ec920;
        }
        if (uVar9 == 3) {
          *puVar4 = 9;
          param_3 = -3;
          piVar6[6] = -0x7dfbc184;
          puVar4[8] = uVar10 >> 3;
          puVar4[7] = uVar16 - 3;
          goto code_r0x825ece60;
        }
      }
      break;
    case 1:
      for (; uVar10 = (uint)uVar15, uVar16 < 0x20; uVar16 = uVar16 + 8) {
        if (uVar12 == 0) goto code_r0x825ece94;
        bVar1 = *pbVar17;
        param_3 = 0;
        uVar12 = uVar12 - 1;
        pbVar17 = pbVar17 + 1;
        uVar15 = (uint)bVar1 << (uVar16 & 0x3f) | uVar15;
      }
      uVar9 = uVar15 & 0xffff;
      if ((~uVar15 << 0x20) >> 0x30 != uVar9) {
        iVar13 = -0x7dfbc170;
code_r0x825eceb8:
        *puVar4 = 9;
        piVar6[6] = iVar13;
        goto code_r0x825ecec0;
      }
      puVar4[1] = (uint)uVar9;
      uVar16 = 0;
      uVar15 = 0;
      if (uVar9 == 0) goto code_r0x825ec910;
      uVar10 = 2;
code_r0x825ec920:
      *puVar4 = uVar10;
      break;
    case 2:
      if (uVar12 == 0) {
code_r0x825ece94:
        puVar4[8] = uVar10;
        puVar4[7] = uVar16;
        piVar6[1] = 0;
        goto code_r0x825ece64;
      }
      if (uVar5 == 0) {
        if (uVar14 == puVar4[0xb]) {
          uVar5 = puVar4[0xc];
          uVar11 = puVar4[10];
          if (uVar5 != uVar11) {
            if (uVar11 < uVar5) {
              uVar5 = (uVar5 - uVar11) - 1;
            }
            else {
              uVar5 = puVar4[0xb] - uVar11;
            }
            uVar14 = uVar11;
            if (uVar5 != 0) goto code_r0x825ec9f0;
          }
        }
        puVar4[0xd] = uVar14;
        param_3 = func_0x825f06e8(puVar4,param_2,param_3);
        uVar14 = puVar4[0xd];
        uVar11 = puVar4[0xc];
        if (uVar14 < uVar11) {
          uVar5 = (uVar11 - uVar14) - 1;
        }
        else {
          uVar5 = puVar4[0xb] - uVar14;
        }
        if ((uVar14 == puVar4[0xb]) && (uVar7 = puVar4[10], uVar11 != uVar7)) {
          uVar14 = uVar7;
          if (uVar7 < uVar11) {
            uVar5 = (uVar11 - uVar7) - 1;
          }
          else {
            uVar5 = puVar4[0xb] - uVar7;
          }
        }
        if (uVar5 == 0) goto code_r0x825ece58;
      }
code_r0x825ec9f0:
      param_3 = 0;
      uVar10 = puVar4[1];
      if (uVar12 < puVar4[1]) {
        uVar10 = uVar12;
      }
      if (uVar5 < uVar10) {
        uVar10 = uVar5;
      }
      func_0x8258e090(uVar14,pbVar17,uVar10);
      uVar11 = puVar4[1];
      pbVar17 = pbVar17 + uVar10;
      uVar12 = uVar12 - uVar10;
      uVar14 = uVar10 + uVar14;
      uVar5 = uVar5 - uVar10;
      puVar4[1] = uVar11 - uVar10;
      if (uVar11 - uVar10 == 0) {
code_r0x825ec910:
        uVar10 = -(uint)(puVar4[6] != 0) & 7;
        goto code_r0x825ec920;
      }
      break;
    case 3:
      for (; uVar10 = (uint)uVar15, uVar16 < 0xe; uVar16 = uVar16 + 8) {
        if (uVar12 == 0) goto code_r0x825ece94;
        bVar1 = *pbVar17;
        param_3 = 0;
        uVar12 = uVar12 - 1;
        pbVar17 = pbVar17 + 1;
        uVar15 = (uint)bVar1 << (uVar16 & 0x3f) | uVar15;
      }
      puVar4[1] = (uint)(uVar15 & 0x3fff);
      if ((0x1d < (uVar15 & 0x1f)) ||
         (uVar9 = ((uVar15 & 0x3fff) << 0x20) >> 0x25 & 0x1f, 0x1d < uVar9)) {
        iVar13 = -0x7dfbc150;
        goto code_r0x825eceb8;
      }
      uVar5 = (*(code *)piVar6[8])(piVar6[10],uVar9 + (uVar15 & 0x1f) + 0x102,4);
      puVar4[3] = uVar5;
      if (uVar5 != 0) {
        puVar4[2] = 0;
        uVar15 = (uVar15 << 0x20) >> 0x2e;
        uVar16 = uVar16 - 0xe;
        *puVar4 = 4;
        goto code_r0x825ecb2c;
      }
      goto code_r0x825ecea8;
    case 4:
code_r0x825ecb2c:
      while (uVar10 = (uint)uVar15, puVar4[2] < (puVar4[1] >> 10) + 4) {
        for (; uVar10 = (uint)uVar15, uVar16 < 3; uVar16 = uVar16 + 8) {
          if (uVar12 == 0) goto code_r0x825ece94;
          bVar1 = *pbVar17;
          param_3 = 0;
          uVar12 = uVar12 - 1;
          pbVar17 = pbVar17 + 1;
          uVar15 = (uint)bVar1 << (uVar16 & 0x3f) | uVar15;
        }
        uVar15 = (uVar15 << 0x20) >> 0x23;
        uVar16 = uVar16 - 3;
        *(uint *)(*(int *)(puVar4[2] * 4 + -0x7dfee740) * 4 + puVar4[3]) = uVar10 & 7;
        puVar4[2] = puVar4[2] + 1;
      }
      while (puVar4[2] < 0x13) {
        *(undefined4 *)(*(int *)(puVar4[2] * 4 + -0x7dfee740) * 4 + puVar4[3]) = 0;
        puVar4[2] = puVar4[2] + 1;
      }
      puVar4[4] = 7;
      lVar3 = func_0x825f0418(puVar4[3],puVar4 + 4,puVar4 + 5,puVar4[9],param_2);
      if (lVar3 == 0) {
        puVar4[2] = 0;
        *puVar4 = 5;
        goto code_r0x825ecd0c;
      }
      iVar13 = (int)lVar3;
      param_3 = lVar3;
code_r0x825eced8:
      if (iVar13 == -3) {
        (*(code *)piVar6[9])(piVar6[10],puVar4[3]);
        *puVar4 = 9;
      }
      goto code_r0x825ece58;
    case 5:
code_r0x825ecd0c:
      while (uVar10 = (uint)uVar15, puVar4[2] < (puVar4[1] >> 5 & 0x1f) + (puVar4[1] & 0x1f) + 0x102
            ) {
        for (; uVar10 = (uint)uVar15, uVar16 < puVar4[4]; uVar16 = uVar16 + 8) {
          if (uVar12 == 0) goto code_r0x825ece94;
          bVar1 = *pbVar17;
          param_3 = 0;
          uVar12 = uVar12 - 1;
          pbVar17 = pbVar17 + 1;
          uVar15 = (uint)bVar1 << (uVar16 & 0x3f) | uVar15;
        }
        iVar13 = (int)((*(uint *)(puVar4[4] * 4 + -0x7dfed3b8) & uVar15) << 3) + puVar4[5];
        uVar5 = *(uint *)(iVar13 + 4);
        bVar1 = *(byte *)(iVar13 + 1);
        uVar11 = (uint)bVar1;
        if (uVar5 < 0x10) {
          uVar16 = uVar16 - uVar11;
          uVar15 = (ulonglong)(uVar10 >> (bVar1 & 0x3f));
          *(uint *)(puVar4[2] * 4 + puVar4[3]) = uVar5;
          puVar4[2] = puVar4[2] + 1;
        }
        else {
          if (uVar5 == 0x12) {
            uVar7 = 7;
            lVar3 = 0xb;
          }
          else {
            uVar7 = uVar5 - 0xe;
            lVar3 = 3;
          }
          for (; uVar10 = (uint)uVar15, uVar16 < uVar7 + uVar11; uVar16 = uVar16 + 8) {
            if (uVar12 == 0) goto code_r0x825ece94;
            bVar2 = *pbVar17;
            param_3 = 0;
            uVar12 = uVar12 - 1;
            pbVar17 = pbVar17 + 1;
            uVar15 = (uint)bVar2 << (uVar16 & 0x3f) | uVar15;
          }
          uVar16 = (uVar16 - uVar7) - uVar11;
          uVar10 = uVar10 >> (bVar1 & 0x3f);
          lVar3 = (ulonglong)(*(uint *)(uVar7 * 4 + -0x7dfed3b8) & uVar10) + lVar3;
          uVar10 = uVar10 >> (uVar7 & 0x3f);
          uVar15 = (ulonglong)uVar10;
          uVar11 = puVar4[2];
          uVar9 = (ulonglong)uVar11;
          if (((ulonglong)(puVar4[1] >> 5) & 0x1f) + ((ulonglong)puVar4[1] & 0x1f) + 0x102 <
              (lVar3 + uVar9 & 0xffffffff)) {
code_r0x825ecefc:
            (*(code *)piVar6[9])(piVar6[10],puVar4[3]);
            iVar13 = -0x7dfbc12c;
            goto code_r0x825eceb8;
          }
          if (uVar5 == 0x10) {
            if (uVar9 == 0) goto code_r0x825ecefc;
            uVar8 = *(undefined4 *)(uVar11 * 4 + puVar4[3] + -4);
          }
          else {
            uVar8 = 0;
          }
          iVar13 = uVar11 << 2;
          do {
            lVar3 = lVar3 + -1;
            uVar9 = uVar9 + 1;
            *(undefined4 *)(puVar4[3] + iVar13) = uVar8;
            iVar13 = iVar13 + 4;
          } while (lVar3 != 0);
          puVar4[2] = (uint)uVar9;
        }
      }
      puVar4[5] = 0;
      uStack_ac = 9;
      uStack_b0 = 6;
      lVar3 = func_0x825f04f8((puVar4[1] & 0x1f) + 0x101,(puVar4[1] >> 5 & 0x1f) + 1,puVar4[3],
                              &uStack_ac,&uStack_b0,auStack_94,&uStack_98,puVar4[9]);
      if (lVar3 != 0) {
        iVar13 = (int)lVar3;
        param_3 = lVar3;
        goto code_r0x825eced8;
      }
      uVar5 = func_0x825ef8e8(uStack_ac,uStack_b0,auStack_94[0],uStack_98,param_2);
      if (uVar5 != 0) {
        puVar4[1] = uVar5;
        (*(code *)piVar6[9])(piVar6[10],puVar4[3]);
        *puVar4 = 6;
        goto code_r0x825ecdb0;
      }
code_r0x825ecea8:
      param_3 = -4;
      goto code_r0x825ece58;
    case 6:
code_r0x825ecdb0:
      puVar4[8] = uVar10;
      puVar4[7] = uVar16;
      iVar13 = *piVar6;
      piVar6[1] = uVar12;
      *piVar6 = (int)pbVar17;
      piVar6[2] = (int)(pbVar17 + (piVar6[2] - iVar13));
      puVar4[0xd] = uVar14;
      param_3 = func_0x825ef948(puVar4,param_2,param_3);
      if ((int)param_3 != 1) goto LAB_8258e008;
      param_3 = 0;
      func_0x825eff88(puVar4[1],param_2);
      uVar14 = puVar4[0xd];
      pbVar17 = (byte *)*piVar6;
      uVar12 = piVar6[1];
      uVar10 = puVar4[8];
      uVar15 = (ulonglong)uVar10;
      uVar16 = puVar4[7];
      if (uVar14 < puVar4[0xc]) {
        uVar5 = (puVar4[0xc] - uVar14) - 1;
      }
      else {
        uVar5 = puVar4[0xb] - uVar14;
      }
      if (puVar4[6] != 0) {
        *puVar4 = 7;
        goto code_r0x825ecf28;
      }
      *puVar4 = 0;
      break;
    case 7:
code_r0x825ecf28:
      puVar4[0xd] = uVar14;
      param_3 = func_0x825f06e8(puVar4,param_2,param_3);
      uVar14 = puVar4[0xd];
      if (puVar4[0xc] == uVar14) {
        *puVar4 = 8;
        goto code_r0x825ecf58;
      }
      goto code_r0x825ece58;
    case 8:
code_r0x825ecf58:
      param_3 = 1;
      goto code_r0x825ece58;
    case 9:
code_r0x825ecec0:
      param_3 = -3;
      goto code_r0x825ece58;
    }
    uVar10 = (uint)uVar15;
    uVar11 = *puVar4;
  }
  param_3 = -2;
code_r0x825ece58:
  puVar4[8] = uVar10;
  puVar4[7] = uVar16;
code_r0x825ece60:
  piVar6[1] = uVar12;
code_r0x825ece64:
  iVar13 = *piVar6;
  *piVar6 = (int)pbVar17;
  piVar6[2] = (int)(pbVar17 + (piVar6[2] - iVar13));
  puVar4[0xd] = uVar14;
LAB_8258e008:
  func_0x825f06e8(puVar4,param_2,param_3);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// ============================================================================
// Test 19: func @ 0x82185b60
// ============================================================================


void test_19(int param_1,int param_2,undefined4 param_3)

{
  int iStack00000014;
  int iStack0000001c;
  undefined4 uStack00000024;
  
  iStack00000014 = param_1;
  iStack0000001c = param_2;
  uStack00000024 = param_3;
  func_0x8214bc60(param_1,param_2,param_3);
  (**(code **)(iStack00000014 + 0x40 + iStack0000001c))(iStack00000014,uStack00000024);
  return;
}



